/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-08-29 21:40:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Doctor;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.DAO.AppointmentDao;
import com.DAO.DoctorDao;
import com.db.DBConnect;
import com.entity.Appointment_entity;
import com.entity.Doctor_entity;
import java.util.*;

public final class comment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/components/cdn-links.jsp", Long.valueOf(1753218954008L));
    _jspx_dependants.put("/Doctor/navbar_doctor.jsp", Long.valueOf(1756498547101L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("com.DAO.AppointmentDao");
    _jspx_imports_classes.add("com.entity.Doctor_entity");
    _jspx_imports_classes.add("com.db.DBConnect");
    _jspx_imports_classes.add("com.DAO.DoctorDao");
    _jspx_imports_classes.add("com.entity.Appointment_entity");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>MediBridge : Comment Page</title>\r\n");
      out.write("<style>\r\n");
      out.write("    * {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("        min-height: 100vh;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .main-content {\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        margin-top: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container {\r\n");
      out.write("        max-width: 700px;\r\n");
      out.write("        margin: 30px auto;\r\n");
      out.write("        background: white;\r\n");
      out.write("        border-radius: 15px;\r\n");
      out.write("        box-shadow: 0 20px 60px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("        animation: slideIn 0.8s ease-out;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes slideIn {\r\n");
      out.write("        from {\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("            transform: translateY(30px);\r\n");
      out.write("        }\r\n");
      out.write("        to {\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("            transform: translateY(0);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-header {\r\n");
      out.write("        background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%);\r\n");
      out.write("        color: white;\r\n");
      out.write("        padding: 25px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        position: relative;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-header h2 {\r\n");
      out.write("        font-size: 28px;\r\n");
      out.write("        font-weight: 300;\r\n");
      out.write("        letter-spacing: 1px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-body {\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-row {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        gap: 20px;\r\n");
      out.write("        margin-bottom: 25px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-group {\r\n");
      out.write("        flex: 1;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-group.full-width {\r\n");
      out.write("        flex: 2;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    label {\r\n");
      out.write("        display: block;\r\n");
      out.write("        margin-bottom: 8px;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        color: #555;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        text-transform: uppercase;\r\n");
      out.write("        letter-spacing: 0.5px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input[type=\"text\"],\r\n");
      out.write("    input[type=\"number\"],\r\n");
      out.write("    input[type=\"tel\"],\r\n");
      out.write("    textarea,\r\n");
      out.write("    select {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding: 15px;\r\n");
      out.write("        border: 2px solid #e1e5e9;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        transition: all 0.3s ease;\r\n");
      out.write("        background: #f8f9fa;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input[type=\"text\"]:focus,\r\n");
      out.write("    input[type=\"number\"]:focus,\r\n");
      out.write("    input[type=\"tel\"]:focus,\r\n");
      out.write("    textarea:focus,\r\n");
      out.write("    select:focus {\r\n");
      out.write("        outline: none;\r\n");
      out.write("        border-color: #4facfe;\r\n");
      out.write("        background: white;\r\n");
      out.write("        box-shadow: 0 0 0 3px rgba(79, 172, 254, 0.1);\r\n");
      out.write("        transform: translateY(-1px);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    textarea {\r\n");
      out.write("        min-height: 120px;\r\n");
      out.write("        resize: vertical;\r\n");
      out.write("        font-family: inherit;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    select {\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .submit-btn {\r\n");
      out.write("        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("        color: white;\r\n");
      out.write("        border: none;\r\n");
      out.write("        padding: 15px 40px;\r\n");
      out.write("        border-radius: 50px;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        transition: all 0.3s ease;\r\n");
      out.write("        display: block;\r\n");
      out.write("        margin: 30px auto 0;\r\n");
      out.write("        min-width: 150px;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .submit-btn::before {\r\n");
      out.write("        content: '';\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        left: -100%;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        background: linear-gradient(90deg, transparent, rgba(255,255,255,0.2), transparent);\r\n");
      out.write("        transition: left 0.5s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .submit-btn:hover::before {\r\n");
      out.write("        left: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .submit-btn:hover {\r\n");
      out.write("        transform: translateY(-2px);\r\n");
      out.write("        box-shadow: 0 10px 25px rgba(102, 126, 234, 0.4);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .submit-btn:active {\r\n");
      out.write("        transform: translateY(0);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Icon styling */\r\n");
      out.write("    .form-header::after {\r\n");
      out.write("        content: '👨‍⚕️';\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: -10px;\r\n");
      out.write("        right: 20px;\r\n");
      out.write("        font-size: 60px;\r\n");
      out.write("        opacity: 0.2;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Responsive design */\r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("        .container {\r\n");
      out.write("            margin: 20px auto;\r\n");
      out.write("            border-radius: 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-row {\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            gap: 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-body {\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-header h2 {\r\n");
      out.write("            font-size: 24px;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Custom styling for better visual hierarchy */\r\n");
      out.write("    .priority-field {\r\n");
      out.write("        border-left: 4px solid #4facfe;\r\n");
      out.write("        padding-left: 16px !important;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .disease-field {\r\n");
      out.write("        border-left: 4px solid #ff6b6b;\r\n");
      out.write("        padding-left: 16px !important;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>MediBridge: Administrator</title>\r\n");
      out.write("    \r\n");
      out.write("   ");
      out.write("<!-- CDN Links File - Include this in your HTML files -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS should come first -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS should come at the end, before closing </body> or in <head> -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery (optional, if needed) -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Popper.js (optional, if using Bootstrap tooltips/popovers separately) -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.8/umd/popper.min.js\"></script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            background-color: #f8f9fa;\r\n");
      out.write("        }\r\n");
      out.write("        .navbar-brand {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-link {\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            transition: color 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-link:hover {\r\n");
      out.write("            color: #ffc107 !important;\r\n");
      out.write("        }\r\n");
      out.write("        .dropdown-menu {\r\n");
      out.write("            border: none;\r\n");
      out.write("            box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15);\r\n");
      out.write("        }\r\n");
      out.write("        .dropdown-item:hover {\r\n");
      out.write("            background-color: #f8f9fa;\r\n");
      out.write("        }\r\n");
      out.write("        .content-area {\r\n");
      out.write("            margin-top: 2rem;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- to solve the issue of back button accessing the admin page you should remove the cache  -->\r\n");

response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");

if(session.getAttribute("doctObj") == null){
	response.sendRedirect("../Doctor.jsp");
}


      out.write("   \r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark border-bottom\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"index.jsp\">\r\n");
      out.write("            <img src=\"../assets/logo.png\" alt=\"Logo\" width=\"35\" height=\"40\" \r\n");
      out.write("                 class=\"d-inline-block align-text-top me-2 rounded-circle\"\r\n");
      out.write("                 onerror=\"this.style.display='none'\">\r\n");
      out.write("            MediBridge\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <!-- Navbar toggler for mobile -->\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" \r\n");
      out.write("                data-bs-target=\"#navbarNavDropdown\" aria-controls=\"navbarNavDropdown\" \r\n");
      out.write("                aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarNavDropdown\">\r\n");
      out.write("            <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("                <li class=\"nav-item me-4\">\r\n");
      out.write("                    <a class=\"nav-link active\" aria-current=\"page\" href=\"Dashboard.jsp\">\r\n");
      out.write("                        <i class=\"fa-solid fa-home me-1\"></i>Home\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("                <li class=\"nav-item me-4\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"Patients.jsp\">\r\n");
      out.write("                        <i class=\"fa-solid fa-user-doctor me-1\"></i>Patient\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("                 \r\n");
      out.write("                <li class=\"nav-item me-4\">\r\n");
      out.write("                     <a class=\"nav-link\" href=\"../doctorLogout\">\r\n");
      out.write("                         <i class=\"fa-solid fa-sign-out-alt me-2\"></i>Logout\r\n");
      out.write("                    </a>\r\n");
      out.write("               </li>       \r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
 int id = Integer.parseInt(request.getParameter("id"));
AppointmentDao dao = new AppointmentDao(DBConnect.getConn());
Appointment_entity ap = dao.getAllDetailsComment(id);

      out.write("\r\n");
      out.write("<div class=\"main-content\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("    <div class=\"form-header\">\r\n");
      out.write("        <h2>Patient Assessment Form</h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"form-body\">\r\n");
      out.write("        <form action=\"submitComment\" method=\"post\">\r\n");
      out.write("            <div class=\"form-row\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"patientName\">Patient Name</label>\r\n");
      out.write("                    <input type=\"text\" id=\"patientName\" name=\"patientName\" readonly\r\n");
      out.write("                           class=\"priority-field\" value=");
      out.print(ap.getApp_name() );
      out.write(" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"age\">Age</label>\r\n");
      out.write("                    <input type=\"number\" id=\"age\" name=\"age\" readonly\r\n");
      out.write("                           min=\"1\" max=\"120\" value=");
      out.print(ap.getApp_age() );
      out.write(" required>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"form-row\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"mobile\">Mobile Number</label>\r\n");
      out.write("                    <input type=\"tel\" id=\"mobile\" name=\"mobile\" readonly\r\n");
      out.write("                           pattern=\"[0-9]{10}\" value=");
      out.print(ap.getApp_contact() );
      out.write(" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"disease\">Primary Condition</label>\r\n");
      out.write("                     <input type=\"text\" readonly value=");
      out.print(ap.getApp_cond() );
      out.write(" class=\"form-control\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"form-row\">\r\n");
      out.write("                <div class=\"form-group full-width\">\r\n");
      out.write("                    <label for=\"comment\">Medical Notes & Observations</label>\r\n");
      out.write("                    <textarea id=\"comment\" name=\"comment\" \r\n");
      out.write("                              placeholder=\"Enter detailed medical observations, treatment notes, patient symptoms, recommended medications, follow-up instructions, etc.\" \r\n");
      out.write("                              required></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <input type=\"hidden\" name=\"id\" value=");
      out.print(ap.getId());
      out.write(">\r\n");
      out.write("                        <input type=\"hidden\" name=\"did\" value=");
      out.print(ap.getDoct_id() );
      out.write(">\r\n");
      out.write("            \r\n");
      out.write("            <button type=\"submit\" class=\"submit-btn\">\r\n");
      out.write("                Submit Assessment\r\n");
      out.write("            </button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
