/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-08-29 21:18:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Doctor;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.DAO.AppointmentDao;
import com.DAO.DoctorDao;
import com.db.DBConnect;
import com.entity.Appointment_entity;
import com.entity.Doctor_entity;
import java.util.*;

public final class Dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/components/cdn-links.jsp", Long.valueOf(1753218954008L));
    _jspx_dependants.put("/Doctor/navbar_doctor.jsp", Long.valueOf(1756498547101L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("com.DAO.AppointmentDao");
    _jspx_imports_classes.add("com.entity.Doctor_entity");
    _jspx_imports_classes.add("com.db.DBConnect");
    _jspx_imports_classes.add("com.DAO.DoctorDao");
    _jspx_imports_classes.add("com.entity.Appointment_entity");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>MediBridge : Doctor Dashboard</title>\r\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        min-height: 100vh;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .welcome-section {\r\n");
      out.write("        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("        color: white;\r\n");
      out.write("        padding: 40px 0;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .welcome-section::before {\r\n");
      out.write("        content: '';\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: -50%;\r\n");
      out.write("        right: -10%;\r\n");
      out.write("        width: 300px;\r\n");
      out.write("        height: 300px;\r\n");
      out.write("        background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("        transform: rotate(45deg);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .welcome-section::after {\r\n");
      out.write("        content: '';\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        bottom: -20%;\r\n");
      out.write("        right: 5%;\r\n");
      out.write("        width: 200px;\r\n");
      out.write("        height: 200px;\r\n");
      out.write("        background: rgba(255, 255, 255, 0.08);\r\n");
      out.write("        border-radius: 15px;\r\n");
      out.write("        transform: rotate(30deg);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .main-container {\r\n");
      out.write("        margin-top: -30px;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        z-index: 10;\r\n");
      out.write("        padding: 30px 0;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .stats-card {\r\n");
      out.write("        background: white;\r\n");
      out.write("        border-radius: 15px;\r\n");
      out.write("        padding: 30px 20px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        margin-bottom: 30px;\r\n");
      out.write("        transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .stats-card:hover {\r\n");
      out.write("        transform: translateY(-5px);\r\n");
      out.write("        box-shadow: 0 15px 40px rgba(0, 0, 0, 0.15);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .stats-card::before {\r\n");
      out.write("        content: '';\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        right: 0;\r\n");
      out.write("        height: 4px;\r\n");
      out.write("        border-radius: 15px 15px 0 0;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .stats-card.appointments::before {\r\n");
      out.write("        background: linear-gradient(90deg, #667eea, #764ba2);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .stats-card.doctors::before {\r\n");
      out.write("        background: linear-gradient(90deg, #f093fb, #f5576c);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .stats-card.specialists::before {\r\n");
      out.write("        background: linear-gradient(90deg, #4facfe, #00f2fe);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .stats-card.patients::before {\r\n");
      out.write("        background: linear-gradient(90deg, #43e97b, #38f9d7);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .stats-icon {\r\n");
      out.write("        width: 70px;\r\n");
      out.write("        height: 70px;\r\n");
      out.write("        border-radius: 15px;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        margin: 0 auto 20px;\r\n");
      out.write("        font-size: 2rem;\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .appointments .stats-icon {\r\n");
      out.write("        background: linear-gradient(135deg, #667eea, #764ba2);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .doctors .stats-icon {\r\n");
      out.write("        background: linear-gradient(135deg, #f093fb, #f5576c);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .specialists .stats-icon {\r\n");
      out.write("        background: linear-gradient(135deg, #4facfe, #00f2fe);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .patients .stats-icon {\r\n");
      out.write("        background: linear-gradient(135deg, #43e97b, #38f9d7);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .stats-number {\r\n");
      out.write("        font-size: 2.5rem;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        color: #2d3748;\r\n");
      out.write("        margin-bottom: 8px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .stats-label {\r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("        color: #718096;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        text-transform: uppercase;\r\n");
      out.write("        letter-spacing: 1px;\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .stats-change {\r\n");
      out.write("        font-size: 0.85rem;\r\n");
      out.write("        font-weight: 500;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .stats-change.positive {\r\n");
      out.write("        color: #38a169;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .stats-change.neutral {\r\n");
      out.write("        color: #718096;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .quick-actions {\r\n");
      out.write("        background: white;\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("        padding: 40px 30px;\r\n");
      out.write("        box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        margin-top: 30px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .section-title {\r\n");
      out.write("        font-size: 1.8rem;\r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("        color: #2d3748;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        margin-bottom: 40px;\r\n");
      out.write("        position: relative;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .section-title::after {\r\n");
      out.write("        content: '';\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        bottom: -10px;\r\n");
      out.write("        left: 50%;\r\n");
      out.write("        transform: translateX(-50%);\r\n");
      out.write("        width: 80px;\r\n");
      out.write("        height: 3px;\r\n");
      out.write("        background: linear-gradient(90deg, #667eea, #764ba2);\r\n");
      out.write("        border-radius: 2px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .action-btn {\r\n");
      out.write("        background: white;\r\n");
      out.write("        border: 2px solid #e2e8f0;\r\n");
      out.write("        border-radius: 12px;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        transition: all 0.3s ease;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: #4a5568;\r\n");
      out.write("        display: block;\r\n");
      out.write("        margin-bottom: 15px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .action-btn:hover {\r\n");
      out.write("        border-color: #667eea;\r\n");
      out.write("        color: #667eea;\r\n");
      out.write("        transform: translateY(-3px);\r\n");
      out.write("        box-shadow: 0 8px 25px rgba(102, 126, 234, 0.2);\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .action-btn i {\r\n");
      out.write("        font-size: 1.5rem;\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .action-btn-text {\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .primary-action {\r\n");
      out.write("        background: linear-gradient(135deg, #667eea, #764ba2);\r\n");
      out.write("        color: white !important;\r\n");
      out.write("        border: none;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .primary-action:hover {\r\n");
      out.write("        background: linear-gradient(135deg, #5a67d8, #6b46c1);\r\n");
      out.write("        color: white !important;\r\n");
      out.write("        border: none;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .welcome-text {\r\n");
      out.write("        position: relative;\r\n");
      out.write("        z-index: 10;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .welcome-title {\r\n");
      out.write("        font-size: 2.5rem;\r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .welcome-subtitle {\r\n");
      out.write("        font-size: 1.2rem;\r\n");
      out.write("        opacity: 0.9;\r\n");
      out.write("        font-weight: 300;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("        .welcome-title {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .stats-number {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .stats-icon {\r\n");
      out.write("            width: 60px;\r\n");
      out.write("            height: 60px;\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .quick-actions {\r\n");
      out.write("            padding: 30px 20px;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>MediBridge: Administrator</title>\r\n");
      out.write("    \r\n");
      out.write("   ");
      out.write("<!-- CDN Links File - Include this in your HTML files -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS should come first -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS should come at the end, before closing </body> or in <head> -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery (optional, if needed) -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Popper.js (optional, if using Bootstrap tooltips/popovers separately) -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.8/umd/popper.min.js\"></script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            background-color: #f8f9fa;\r\n");
      out.write("        }\r\n");
      out.write("        .navbar-brand {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-link {\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            transition: color 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-link:hover {\r\n");
      out.write("            color: #ffc107 !important;\r\n");
      out.write("        }\r\n");
      out.write("        .dropdown-menu {\r\n");
      out.write("            border: none;\r\n");
      out.write("            box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15);\r\n");
      out.write("        }\r\n");
      out.write("        .dropdown-item:hover {\r\n");
      out.write("            background-color: #f8f9fa;\r\n");
      out.write("        }\r\n");
      out.write("        .content-area {\r\n");
      out.write("            margin-top: 2rem;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- to solve the issue of back button accessing the admin page you should remove the cache  -->\r\n");

response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");

if(session.getAttribute("doctObj") == null){
	response.sendRedirect("../Doctor.jsp");
}


      out.write("   \r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark border-bottom\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"index.jsp\">\r\n");
      out.write("            <img src=\"../assets/logo.png\" alt=\"Logo\" width=\"35\" height=\"40\" \r\n");
      out.write("                 class=\"d-inline-block align-text-top me-2 rounded-circle\"\r\n");
      out.write("                 onerror=\"this.style.display='none'\">\r\n");
      out.write("            MediBridge\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <!-- Navbar toggler for mobile -->\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" \r\n");
      out.write("                data-bs-target=\"#navbarNavDropdown\" aria-controls=\"navbarNavDropdown\" \r\n");
      out.write("                aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarNavDropdown\">\r\n");
      out.write("            <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("                <li class=\"nav-item me-4\">\r\n");
      out.write("                    <a class=\"nav-link active\" aria-current=\"page\" href=\"Dashboard.jsp\">\r\n");
      out.write("                        <i class=\"fa-solid fa-home me-1\"></i>Home\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("                <li class=\"nav-item me-4\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"Patients.jsp\">\r\n");
      out.write("                        <i class=\"fa-solid fa-user-doctor me-1\"></i>Patient\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("                 \r\n");
      out.write("                <li class=\"nav-item me-4\">\r\n");
      out.write("                     <a class=\"nav-link\" href=\"../doctorLogout\">\r\n");
      out.write("                         <i class=\"fa-solid fa-sign-out-alt me-2\"></i>Logout\r\n");
      out.write("                    </a>\r\n");
      out.write("               </li>       \r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- Welcome Section -->\r\n");
      out.write("    <div class=\"welcome-section\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"welcome-text\">\r\n");
      out.write("                <div class=\"d-flex align-items-center\">\r\n");
      out.write("                    <div class=\"stats-icon me-3\">\r\n");
      out.write("                        <i class=\"fas fa-user-md\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <h1 class=\"welcome-title\">Welcome,Doctor</h1>\r\n");
      out.write("                        <p class=\"welcome-subtitle\">Hospital Management System - Doctor Dashboard</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Main Container -->\r\n");
      out.write("    <div class=\"container main-container\">\r\n");
      out.write("        <!-- Statistics Cards -->\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <div class=\"stats-card appointments\">\r\n");
      out.write("                    <div class=\"stats-icon\">\r\n");
      out.write("                        <i class=\"fas fa-calendar-check\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"stats-number\">247</div>\r\n");
      out.write("                    <div class=\"stats-label\">Total Appointments</div>\r\n");
      out.write("                    <div class=\"stats-change positive\">+12% from last month</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <div class=\"stats-card doctors\">\r\n");
      out.write("                    <div class=\"stats-icon\">\r\n");
      out.write("                        <i class=\"fas fa-user-md\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"stats-number\">32</div>\r\n");
      out.write("                    <div class=\"stats-label\">Active Doctors</div>\r\n");
      out.write("                    <div class=\"stats-change positive\">+2 new this month</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <div class=\"stats-card specialists\">\r\n");
      out.write("                    <div class=\"stats-icon\">\r\n");
      out.write("                        <i class=\"fas fa-stethoscope\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"stats-number\">15</div>\r\n");
      out.write("                    <div class=\"stats-label\">Specialists</div>\r\n");
      out.write("                    <div class=\"stats-change neutral\">No change</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                <div class=\"stats-card patients\">\r\n");
      out.write("                    <div class=\"stats-icon\">\r\n");
      out.write("                        <i class=\"fas fa-users\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"stats-number\">1,842</div>\r\n");
      out.write("                    <div class=\"stats-label\">Registered Patients</div>\r\n");
      out.write("                    <div class=\"stats-change positive\">+156 this month</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Quick Actions Section -->\r\n");
      out.write("        <div class=\"quick-actions\">\r\n");
      out.write("            <h2 class=\"section-title\">Quick Actions</h2>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("                    <a href=\"Patients.jsp\" class=\"action-btn primary-action\">\r\n");
      out.write("                        <i class=\"fas fa-plus\"></i>\r\n");
      out.write("                        <div class=\"action-btn-text\">View Appointments</div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("                    <a href=\"#\" class=\"action-btn\">\r\n");
      out.write("                        <i class=\"fas fa-user-plus\"></i>\r\n");
      out.write("                        <div class=\"action-btn-text\">View Doctors</div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("               \r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("                    <a href=\"#\" class=\"action-btn\">\r\n");
      out.write("                        <i class=\"fas fa-stethoscope\"></i>\r\n");
      out.write("                        <div class=\"action-btn-text\">Add Specialist</div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("                    <a href=\"#\" class=\"action-btn\">\r\n");
      out.write("                        <i class=\"fas fa-stethoscope\"></i>\r\n");
      out.write("                        <div class=\"action-btn-text\">View Feedback</div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
