/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-08-30 14:41:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Change_005fpassword_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/../components/cdn-links.jsp", Long.valueOf(1753218954008L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Reset Password - MediBridge</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- CDN Links File - Include this in your HTML files -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS should come first -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS should come at the end, before closing </body> or in <head> -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery (optional, if needed) -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Popper.js (optional, if using Bootstrap tooltips/popovers separately) -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.8/umd/popper.min.js\"></script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("        min-height: 100vh;\r\n");
      out.write("        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .reset-container {\r\n");
      out.write("        min-height: 100vh;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .reset-card {\r\n");
      out.write("        background: white;\r\n");
      out.write("        border-radius: 15px;\r\n");
      out.write("        box-shadow: 0 20px 40px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        padding: 40px;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        max-width: 450px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .reset-title {\r\n");
      out.write("        color: #333;\r\n");
      out.write("        font-size: 28px;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .reset-subtitle {\r\n");
      out.write("        color: #666;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        margin-bottom: 30px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .form-label {\r\n");
      out.write("        color: #333;\r\n");
      out.write("        font-weight: 500;\r\n");
      out.write("        margin-bottom: 8px;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .form-control {\r\n");
      out.write("        border: 2px solid #e1e5e9;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        padding: 12px 15px;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        transition: all 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .form-control:focus {\r\n");
      out.write("        border-color: #667eea;\r\n");
      out.write("        box-shadow: 0 0 0 0.2rem rgba(102, 126, 234, 0.25);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .btn-reset {\r\n");
      out.write("        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        padding: 12px;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        transition: all 0.3s ease;\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .btn-reset:hover {\r\n");
      out.write("        transform: translateY(-2px);\r\n");
      out.write("        box-shadow: 0 8px 25px rgba(102, 126, 234, 0.3);\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .back-to-login {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .back-to-login a {\r\n");
      out.write("        color: #667eea;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        font-weight: 500;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .back-to-login a:hover {\r\n");
      out.write("        color: #764ba2;\r\n");
      out.write("        text-decoration: underline;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .step-indicator {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        margin-bottom: 30px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .step {\r\n");
      out.write("        width: 8px;\r\n");
      out.write("        height: 8px;\r\n");
      out.write("        border-radius: 50%;\r\n");
      out.write("        background: #e1e5e9;\r\n");
      out.write("        margin: 0 4px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .step.active {\r\n");
      out.write("        background: #667eea;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .alert {\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class=\"reset-container\">\r\n");
      out.write("    <div class=\"reset-card\">\r\n");
      out.write("        <div class=\"step-indicator\">\r\n");
      out.write("            <div class=\"step active\"></div>\r\n");
      out.write("            <div class=\"step\"></div>\r\n");
      out.write("            <div class=\"step\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <h2 class=\"reset-title\">Reset Password</h2>\r\n");
      out.write("        <p class=\"reset-subtitle\">Enter your email address and we'll send you a link to reset your password.</p>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Success/Error Messages -->\r\n");
      out.write("        ");
 if(request.getParameter("success") != null) { 
      out.write("\r\n");
      out.write("            <div class=\"alert alert-success\" role=\"alert\">\r\n");
      out.write("                <i class=\"fas fa-check-circle me-2\"></i>\r\n");
      out.write("                Password reset link has been sent to your email address.\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        ");
 if(request.getParameter("error") != null) { 
      out.write("\r\n");
      out.write("            <div class=\"alert alert-danger\" role=\"alert\">\r\n");
      out.write("                <i class=\"fas fa-exclamation-circle me-2\"></i>\r\n");
      out.write("                Email address not found. Please check and try again.\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <form action=\"forgot-password\" method=\"post\" id=\"resetForm\">\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"email\" class=\"form-label\">Email Address</label>\r\n");
      out.write("                <input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" \r\n");
      out.write("                       placeholder=\"Enter your registered email\" required>\r\n");
      out.write("                <div class=\"invalid-feedback\">\r\n");
      out.write("                    Please enter a valid email address.\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-reset\">\r\n");
      out.write("                <i class=\"fas fa-paper-plane me-2\"></i>\r\n");
      out.write("                Send Reset Link\r\n");
      out.write("            </button>\r\n");
      out.write("        </form>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"back-to-login\">\r\n");
      out.write("            <a href=\"doctor-login.jsp\">\r\n");
      out.write("                <i class=\"fas fa-arrow-left me-1\"></i>\r\n");
      out.write("                Back to Login\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    // Form validation\r\n");
      out.write("    document.getElementById('resetForm').addEventListener('submit', function(e) {\r\n");
      out.write("        const email = document.getElementById('email');\r\n");
      out.write("        const emailPattern = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;\r\n");
      out.write("        \r\n");
      out.write("        if (!emailPattern.test(email.value)) {\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("            email.classList.add('is-invalid');\r\n");
      out.write("        } else {\r\n");
      out.write("            email.classList.remove('is-invalid');\r\n");
      out.write("            email.classList.add('is-valid');\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    // Real-time email validation\r\n");
      out.write("    document.getElementById('email').addEventListener('input', function() {\r\n");
      out.write("        const email = this;\r\n");
      out.write("        const emailPattern = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;\r\n");
      out.write("        \r\n");
      out.write("        if (emailPattern.test(email.value)) {\r\n");
      out.write("            email.classList.remove('is-invalid');\r\n");
      out.write("            email.classList.add('is-valid');\r\n");
      out.write("        } else {\r\n");
      out.write("            email.classList.remove('is-valid');\r\n");
      out.write("            if (email.value.length > 0) {\r\n");
      out.write("                email.classList.add('is-invalid');\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
