/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-07-22 21:19:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.db.DBConnect;
import java.sql.Connection;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/components/cdn-links.jsp", Long.valueOf(1753218954008L));
    _jspx_dependants.put("/components/navbar.jsp", Long.valueOf(1752418759867L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("com.db.DBConnect");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>MediBridge | HomePage</title>\r\n");
      out.write("    <!-- Include CDN links from external file -->\r\n");
      out.write("<!-- CDN Links File - Include this in your HTML files -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS should come first -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS should come at the end, before closing </body> or in <head> -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery (optional, if needed) -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Popper.js (optional, if using Bootstrap tooltips/popovers separately) -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.8/umd/popper.min.js\"></script>");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        .hero-section {\r\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 100px 0;\r\n");
      out.write("        }\r\n");
      out.write("        .feature-card {\r\n");
      out.write("            transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("        .feature-card:hover {\r\n");
      out.write("            transform: translateY(-10px);\r\n");
      out.write("            box-shadow: 0 20px 40px rgba(0,0,0,0.1);\r\n");
      out.write("        }\r\n");
      out.write("        .doctor-card {\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            transition: transform 0.3s ease;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        .doctor-card:hover {\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("        }\r\n");
      out.write("        .doctor-img {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 250px;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("        }\r\n");
      out.write("        .review-card {\r\n");
      out.write("            background: #f8f9fa;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("            margin: 1rem 0;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        .stars {\r\n");
      out.write("            color: #ffc107;\r\n");
      out.write("        }\r\n");
      out.write("        .contact-section {\r\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        .footer {\r\n");
      out.write("            background: #2c3e50;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        .carousel-item {\r\n");
      out.write("            height: 500px;\r\n");
      out.write("        }\r\n");
      out.write("        .carousel-item img {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("        }\r\n");
      out.write("        .section-title {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 3rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("        .section-title::after {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            bottom: -10px;\r\n");
      out.write("            left: 50%;\r\n");
      out.write("            transform: translateX(-50%);\r\n");
      out.write("            width: 80px;\r\n");
      out.write("            height: 3px;\r\n");
      out.write("            background: #007bff;\r\n");
      out.write("        }\r\n");
      out.write("        .feature-icon {\r\n");
      out.write("            font-size: 3rem;\r\n");
      out.write("            color: #007bff;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-custom {\r\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            padding: 10px 30px;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-custom:hover {\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 10px 20px rgba(0,0,0,0.2);\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Include Navbar -->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Fixed Navbar</title>\r\n");
      out.write("<!-- Include CDN links from external file -->\r\n");
      out.write("<!-- CDN Links File - Include this in your HTML files -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS should come first -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS should come at the end, before closing </body> or in <head> -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery (optional, if needed) -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Popper.js (optional, if using Bootstrap tooltips/popovers separately) -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.8/umd/popper.min.js\"></script>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark border-bottom\">\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("<a class=\"navbar-brand\" href=\"index.jsp\">\r\n");
      out.write("<img src=\"assets/logo.png\" alt=\"Logo\" width=\"35\" height=\"40\" class=\"d-inline-block align-text-top me-2 rounded-circle\" \r\n");
      out.write("     onerror=\"this.style.display='none'\">\r\n");
      out.write("MediBridge\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("<!-- Navbar toggler for mobile -->\r\n");
      out.write("<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNavDropdown\" aria-controls=\"navbarNavDropdown\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("</button>\r\n");
      out.write("\r\n");
      out.write("<div class=\"collapse navbar-collapse\" id=\"navbarNavDropdown\">\r\n");
      out.write("<ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("<li class=\"nav-item me-4\">\r\n");
      out.write("<a class=\"nav-link active\" aria-current=\"page\" href=\"Admin.jsp\">\r\n");
      out.write("<i class=\"fa-solid fa-user-shield me-1\"></i>Admin\r\n");
      out.write("</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li class=\"nav-item me-4\">\r\n");
      out.write("<a class=\"nav-link\" href=\"Apointment.jsp\">\r\n");
      out.write("<i class=\"fa-solid fa-calendar-check me-1\"></i>Appointment\r\n");
      out.write("</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li class=\"nav-item me-4\">\r\n");
      out.write("<a class=\"nav-link\" href=\"User.jsp\">\r\n");
      out.write("<i class=\"fa-solid fa-user me-1\"></i>User\r\n");
      out.write("</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li class=\"nav-item me-4\">\r\n");
      out.write("<a class=\"nav-link\" href=\"Doctor.jsp\">\r\n");
      out.write("<i class=\"fa-solid fa-user-doctor me-1\"></i>Doctor\r\n");
      out.write("</a>\r\n");
      out.write("</li>\r\n");
      out.write("<li class=\"nav-item\">\r\n");
      out.write("<a class=\"nav-link\" href=\"#\">\r\n");
      out.write("<i class=\"fa-solid fa-user-circle\"></i>\r\n");
      out.write("</a>\r\n");
      out.write("</li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- Scripts are included in CDN file -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
 Connection conn = DBConnect.getConn(); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Image Carousel -->\r\n");
      out.write("    <div id=\"hospitalCarousel\" class=\"carousel slide\" data-bs-ride=\"carousel\">\r\n");
      out.write("        <div class=\"carousel-indicators\">\r\n");
      out.write("            <button type=\"button\" data-bs-target=\"#hospitalCarousel\" data-bs-slide-to=\"0\" class=\"active\"></button>\r\n");
      out.write("            <button type=\"button\" data-bs-target=\"#hospitalCarousel\" data-bs-slide-to=\"1\"></button>\r\n");
      out.write("            <button type=\"button\" data-bs-target=\"#hospitalCarousel\" data-bs-slide-to=\"2\"></button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"carousel-inner\">\r\n");
      out.write("            <div class=\"carousel-item active\">\r\n");
      out.write("                <img src=\"https://images.unsplash.com/photo-1551190822-a9333d879b1f?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80\" class=\"d-block w-100\" alt=\"Hospital Building\">\r\n");
      out.write("                <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                    <h2>Welcome to MediBridge</h2>\r\n");
      out.write("                    <p>Your trusted partner in healthcare management</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"carousel-item\">\r\n");
      out.write("                <img src=\"https://images.unsplash.com/photo-1538108149393-fbbd81895907?ixlib=rb-4.0.3&auto=format&fit=crop&w=2128&q=80\" class=\"d-block w-100\" alt=\"Medical Team\">\r\n");
      out.write("                <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                    <h2>Expert Medical Team</h2>\r\n");
      out.write("                    <p>Dedicated professionals committed to your health</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"carousel-item\">\r\n");
      out.write("                <img src=\"https://images.unsplash.com/photo-1559757148-5c350d0d3c56?ixlib=rb-4.0.3&auto=format&fit=crop&w=2131&q=80\" class=\"d-block w-100\" alt=\"Modern Equipment\">\r\n");
      out.write("                <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                    <h2>Modern Medical Equipment</h2>\r\n");
      out.write("                    <p>State-of-the-art technology for better healthcare</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#hospitalCarousel\" data-bs-slide=\"prev\">\r\n");
      out.write("            <span class=\"carousel-control-prev-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#hospitalCarousel\" data-bs-slide=\"next\">\r\n");
      out.write("            <span class=\"carousel-control-next-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Key Features Section -->\r\n");
      out.write("    <section class=\"py-5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <h2 class=\"section-title\">Our Key Features</h2>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6 mb-4\">\r\n");
      out.write("                    <div class=\"card feature-card text-center\">\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <i class=\"fas fa-calendar-check feature-icon\"></i>\r\n");
      out.write("                            <h4 class=\"card-title\">Easy Appointment Booking</h4>\r\n");
      out.write("                            <p class=\"card-text\">Book appointments with your preferred doctors online. Quick, easy, and convenient scheduling system.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6 mb-4\">\r\n");
      out.write("                    <div class=\"card feature-card text-center\">\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <i class=\"fas fa-user-md feature-icon\"></i>\r\n");
      out.write("                            <h4 class=\"card-title\">Expert Doctors</h4>\r\n");
      out.write("                            <p class=\"card-text\">Our team of experienced & qualified doctors provide the best medical care with modern treatments.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6 mb-4\">\r\n");
      out.write("                    <div class=\"card feature-card text-center\">\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <i class=\"fas fa-ambulance feature-icon\"></i>\r\n");
      out.write("                            <h4 class=\"card-title\">Emergency Services</h4>\r\n");
      out.write("                            <p class=\"card-text\">24/7 emergency medical services with rapid response team and state-of-the-art emergency equipment.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6 mb-4\">\r\n");
      out.write("                    <div class=\"card feature-card text-center\">\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <i class=\"fas fa-pills feature-icon\"></i>\r\n");
      out.write("                            <h4 class=\"card-title\">Pharmacy Services</h4>\r\n");
      out.write("                            <p class=\"card-text\">In-house pharmacy with all essential medicines and prescriptions fulfilled with quality assurance.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6 mb-4\">\r\n");
      out.write("                    <div class=\"card feature-card text-center\">\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <i class=\"fas fa-microscope feature-icon\"></i>\r\n");
      out.write("                            <h4 class=\"card-title\">Advanced Lab Tests</h4>\r\n");
      out.write("                            <p class=\"card-text\">Modern laboratory facilities with accurate diagnostic tests and quick result delivery.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6 mb-4\">\r\n");
      out.write("                    <div class=\"card feature-card text-center\">\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <i class=\"fas fa-bed feature-icon\"></i>\r\n");
      out.write("                            <h4 class=\"card-title\">Comfortable Rooms</h4>\r\n");
      out.write("                            <p class=\"card-text\">Well-equipped patient rooms with modern amenities for comfortable stay during treatment.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Our Great Doctors Section -->\r\n");
      out.write("    <section class=\"py-5 bg-light\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <h2 class=\"section-title\">Our Great Doctors</h2>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("                    <div class=\"card doctor-card\">\r\n");
      out.write("                        <img src=\"assets/doctor_1.jpeg\" class=\"doctor-img\" alt=\" Dr. Michael Chen\">\r\n");
      out.write("                        <div class=\"card-body text-center\">\r\n");
      out.write("                            <h5 class=\"card-title\">Dr. Sarah Johnson</h5>\r\n");
      out.write("                            <p class=\"text-muted\">Cardiologist</p>\r\n");
      out.write("                            <p class=\"small\">MBBS, MD Cardiology</p>\r\n");
      out.write("                            <p class=\"card-text\">\"Dedicated to providing exceptional cardiac care with compassion, cutting-edge technology, and unmatched expertise.\"</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("                    <div class=\"card doctor-card\">\r\n");
      out.write("                        <img src=\"assets/doctor_2.jpeg\" class=\"doctor-img\" alt=\"Dr. Sarah Johnson\">\r\n");
      out.write("                        <div class=\"card-body text-center\">\r\n");
      out.write("                            <h5 class=\"card-title\">Dr. Michael Chen</h5>\r\n");
      out.write("                            <p class=\"text-muted\">Neurologist</p>\r\n");
      out.write("                            <p class=\"small\">MBBS, MD Neurology</p>\r\n");
      out.write("                            <p class=\"card-text\">\"Committed to advancing neurological care through innovation and patient-centered treatment.\"</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("                    <div class=\"card doctor-card\">\r\n");
      out.write("                        <img src=\"assets/doctor_3.jpeg\" class=\"doctor-img\" alt=\"Dr. James Wilson\">\r\n");
      out.write("                        <div class=\"card-body text-center\">\r\n");
      out.write("                            <h5 class=\"card-title\">Dr. Emily Rodriguez</h5>\r\n");
      out.write("                            <p class=\"text-muted\">Pediatrician</p>\r\n");
      out.write("                            <p class=\"small\">MBBS, MD Pediatrics</p>\r\n");
      out.write("                            <p class=\"card-text\">\"Ensuring the health and happiness of children with gentle and comprehensive care.\"</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("                    <div class=\"card doctor-card\">\r\n");
      out.write("                        <img src=\"assets/doctor_4.jpeg\" class=\"doctor-img\" alt=\"Dr. Emily Rodriguez\">\r\n");
      out.write("                        <div class=\"card-body text-center\">\r\n");
      out.write("                            <h5 class=\"card-title\">Dr. James Wilson</h5>\r\n");
      out.write("                            <p class=\"text-muted\">Orthopedic Surgeon</p>\r\n");
      out.write("                            <p class=\"small\">MBBS, MS Orthopedics</p>\r\n");
      out.write("                            <p class=\"card-text\">\"Specializing in advanced orthopedic procedures to restore mobility and improve quality of life.\"</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Reviews Section -->\r\n");
      out.write("    <section class=\"py-5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <h2 class=\"section-title\">What Our Patients Say</h2>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-4 mb-4\">\r\n");
      out.write("                    <div class=\"review-card\">\r\n");
      out.write("                        <div class=\"stars mb-2\">\r\n");
      out.write("                            <i class=\"fas fa-star\"></i>\r\n");
      out.write("                            <i class=\"fas fa-star\"></i>\r\n");
      out.write("                            <i class=\"fas fa-star\"></i>\r\n");
      out.write("                            <i class=\"fas fa-star\"></i>\r\n");
      out.write("                            <i class=\"fas fa-star\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p class=\"mb-3\">\"Excellent service and professional staff. The doctors are very knowledgeable and caring. I highly recommend MediBridge for all healthcare needs.\"</p>\r\n");
      out.write("                        <div class=\"d-flex align-items-center\">\r\n");
      out.write("                            <img src=assets/doctor_1.jpeg class=\"rounded-circle me-3\" width=\"50\" height=\"50\" alt=\"Patient\">\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <h6 class=\"mb-0\">Maria Garcia</h6>\r\n");
      out.write("                                <small class=\"text-muted\">Patient</small>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 mb-4\">\r\n");
      out.write("                    <div class=\"review-card\">\r\n");
      out.write("                        <div class=\"stars mb-2\">\r\n");
      out.write("                            <i class=\"fas fa-star\"></i>\r\n");
      out.write("                            <i class=\"fas fa-star\"></i>\r\n");
      out.write("                            <i class=\"fas fa-star\"></i>\r\n");
      out.write("                            <i class=\"fas fa-star\"></i>\r\n");
      out.write("                            <i class=\"fas fa-star\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p class=\"mb-3\">\"The online appointment system is fantastic! Easy to use and the doctors are always on time. Great experience overall.\"</p>\r\n");
      out.write("                        <div class=\"d-flex align-items-center\">\r\n");
      out.write("                            <img src=\"assets/doctor_3.jpeg\" class=\"rounded-circle me-3\" width=\"50\" height=\"50\" alt=\"Patient\">\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <h6 class=\"mb-0\">John Smith</h6>\r\n");
      out.write("                                <small class=\"text-muted\">Patient</small>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 mb-4\">\r\n");
      out.write("                    <div class=\"review-card\">\r\n");
      out.write("                        <div class=\"stars mb-2\">\r\n");
      out.write("                            <i class=\"fas fa-star\"></i>\r\n");
      out.write("                            <i class=\"fas fa-star\"></i>\r\n");
      out.write("                            <i class=\"fas fa-star\"></i>\r\n");
      out.write("                            <i class=\"fas fa-star\"></i>\r\n");
      out.write("                            <i class=\"fas fa-star\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p class=\"mb-3\">\"Clean facilities, modern equipment, and compassionate care. MediBridge has exceeded my expectations in every way.\"</p>\r\n");
      out.write("                        <div class=\"d-flex align-items-center\">\r\n");
      out.write("                            <img src=\"https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&q=100\" class=\"rounded-circle me-3\" width=\"50\" height=\"50\" alt=\"Patient\">\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <h6 class=\"mb-0\">Lisa Anderson</h6>\r\n");
      out.write("                                <small class=\"text-muted\">Patient</small>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Contact Us Section -->\r\n");
      out.write("    <section class=\"py-5 contact-section\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <h2 class=\"section-title text-white\">Contact Us</h2>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-8 mx-auto\">\r\n");
      out.write("                    <form>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" placeholder=\"Your Name\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                <input type=\"email\" class=\"form-control\" placeholder=\"Your Email\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" placeholder=\"Subject\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <textarea class=\"form-control\" rows=\"5\" placeholder=\"Your Message\" required></textarea>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"text-center\">\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-custom btn-lg\">Send Message</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <footer class=\"footer py-5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-4 mb-4\">\r\n");
      out.write("                    <h5>MediBridge</h5>\r\n");
      out.write("                    <p>Your trusted partner in healthcare management. We provide comprehensive medical services with modern technology and compassionate care.</p>\r\n");
      out.write("                    <div class=\"social-links\">\r\n");
      out.write("                        <a href=\"#\" class=\"text-white me-3\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                        <a href=\"#\" class=\"text-white me-3\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                        <a href=\"#\" class=\"text-white me-3\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                        <a href=\"#\" class=\"text-white me-3\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-2 mb-4\">\r\n");
      out.write("                    <h6>Quick Links</h6>\r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li><a href=\"#\" class=\"text-white-50\">Home</a></li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"text-white-50\">About</a></li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"text-white-50\">Services</a></li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"text-white-50\">Doctors</a></li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"text-white-50\">Contact</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 mb-4\">\r\n");
      out.write("                    <h6>Services</h6>\r\n");
      out.write("                    <ul class=\"list-unstyled\">\r\n");
      out.write("                        <li><a href=\"#\" class=\"text-white-50\">Emergency Care</a></li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"text-white-50\">Surgery</a></li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"text-white-50\">Laboratory</a></li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"text-white-50\">Pharmacy</a></li>\r\n");
      out.write("                        <li><a href=\"#\" class=\"text-white-50\">Cardiology</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 mb-4\">\r\n");
      out.write("                    <h6>Contact Info</h6>\r\n");
      out.write("                    <ul class=\"list-unstyled text-white-50\">\r\n");
      out.write("                        <li><i class=\"fas fa-map-marker-alt me-2\"></i>123 Medical Street, Nagpur , Maharashtra</li>\r\n");
      out.write("                        <li><i class=\"fas fa-phone me-2\"></i>+91-1234567891</li>\r\n");
      out.write("                        <li><i class=\"fas fa-envelope me-2\"></i>info@medibridge.com</li>\r\n");
      out.write("                    </ul>	\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr class=\"my-4\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12 text-center\">\r\n");
      out.write("                    <p class=\"text-white-50 mb-0\">&copy; 2024 MediBridge. All rights reserved.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    <!-- Scripts are included in CDN file -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
