/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-08-31 14:34:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Redirection_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/components/cdn-links.jsp", Long.valueOf(1753218954008L));
    _jspx_dependants.put("/components/navbar.jsp", Long.valueOf(1756650841613L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>MediBridge : Appointment</title>\r\n");
      out.write("<style>\r\n");
      out.write("    * {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    body {\r\n");
      out.write("        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("        min-height: 100vh;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /* Main Content */\r\n");
      out.write("    .main-content {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        padding: 2rem;\r\n");
      out.write("        min-height: calc(100vh - 80px);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .welcome-card {\r\n");
      out.write("        background: rgba(255, 255, 255, 0.95);\r\n");
      out.write("        backdrop-filter: blur(10px);\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("        padding: 3rem;\r\n");
      out.write("        box-shadow: 0 20px 40px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        max-width: 500px;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        border: 1px solid rgba(255, 255, 255, 0.2);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .welcome-card h1 {\r\n");
      out.write("        color: #2d3748;\r\n");
      out.write("        font-size: 2.5rem;\r\n");
      out.write("        margin-bottom: 1rem;\r\n");
      out.write("        background: linear-gradient(135deg, #667eea, #764ba2);\r\n");
      out.write("        -webkit-background-clip: text;\r\n");
      out.write("        -webkit-text-fill-color: transparent;\r\n");
      out.write("        background-clip: text;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .welcome-card p {\r\n");
      out.write("        color: #4a5568;\r\n");
      out.write("        font-size: 1.1rem;\r\n");
      out.write("        line-height: 1.6;\r\n");
      out.write("        margin-bottom: 2rem;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .auth-buttons {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        gap: 1rem;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .btn {\r\n");
      out.write("        padding: 0.875rem 2rem;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 12px;\r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        transition: all 0.3s ease;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .btn-primary {\r\n");
      out.write("        background: linear-gradient(135deg, #667eea, #764ba2);\r\n");
      out.write("        color: white;\r\n");
      out.write("        box-shadow: 0 4px 15px rgba(102, 126, 234, 0.3);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .btn-primary:hover {\r\n");
      out.write("        transform: translateY(-2px);\r\n");
      out.write("        box-shadow: 0 6px 20px rgba(102, 126, 234, 0.4);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .btn-secondary {\r\n");
      out.write("        background: transparent;\r\n");
      out.write("        color: #667eea;\r\n");
      out.write("        border: 2px solid #667eea;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .btn-secondary:hover {\r\n");
      out.write("        background: #667eea;\r\n");
      out.write("        color: white;\r\n");
      out.write("        transform: translateY(-2px);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .features {\r\n");
      out.write("        display: grid;\r\n");
      out.write("        grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));\r\n");
      out.write("        gap: 1.5rem;\r\n");
      out.write("        margin-top: 2rem;\r\n");
      out.write("        padding-top: 2rem;\r\n");
      out.write("        border-top: 1px solid rgba(102, 126, 234, 0.2);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .feature {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        padding: 1rem;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .feature-icon {\r\n");
      out.write("        width: 60px;\r\n");
      out.write("        height: 60px;\r\n");
      out.write("        background: linear-gradient(135deg, #667eea, #764ba2);\r\n");
      out.write("        border-radius: 50%;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        margin: 0 auto 1rem;\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-size: 1.5rem;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .feature h3 {\r\n");
      out.write("        color: #2d3748;\r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("        margin-bottom: 0.5rem;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .feature p {\r\n");
      out.write("        color: #718096;\r\n");
      out.write("        font-size: 0.875rem;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("        .welcome-card {\r\n");
      out.write("            margin: 1rem;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .welcome-card h1 {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .features {\r\n");
      out.write("            grid-template-columns: 1fr;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Fixed Navbar</title>\r\n");
      out.write("<!-- Include CDN links from external file -->\r\n");
      out.write("<!-- CDN Links File - Include this in your HTML files -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS should come first -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS should come at the end, before closing </body> or in <head> -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery (optional, if needed) -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Popper.js (optional, if using Bootstrap tooltips/popovers separately) -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.8/umd/popper.min.js\"></script>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark border-bottom\">\r\n");
      out.write("		<div class=\"container-fluid\">\r\n");
      out.write("			<a class=\"navbar-brand\" href=\"index.jsp\"> <img\r\n");
      out.write("				src=\"assets/logo.png\" alt=\"Logo\" width=\"40\" height=\"40\"\r\n");
      out.write("				class=\"d-inline-block align-text-top me-2 rounded-circle\"\r\n");
      out.write("				onerror=\"this.style.display='none'\">\r\n");
      out.write("			</a>\r\n");
      out.write("			<h4 style=color:white>MediBridge</h4>\r\n");
      out.write("\r\n");
      out.write("			<!-- Navbar toggler for mobile -->\r\n");
      out.write("			<button class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("				data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNavDropdown\"\r\n");
      out.write("				aria-controls=\"navbarNavDropdown\" aria-expanded=\"false\"\r\n");
      out.write("				aria-label=\"Toggle navigation\">\r\n");
      out.write("				<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("			</button>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"navbarNavDropdown\">\r\n");
      out.write("				<ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("					<li class=\"nav-item me-4\"><a class=\"nav-link active\"\r\n");
      out.write("						aria-current=\"page\" href=\"Admin.jsp\"> <i\r\n");
      out.write("							class=\"fa-solid fa-user-shield me-1\"></i>Admin\r\n");
      out.write("					</a></li>\r\n");
      out.write("					<li class=\"nav-item me-4\"><a class=\"nav-link\"\r\n");
      out.write("						href=\"Redirection.jsp\"> <i\r\n");
      out.write("							class=\"fa-solid fa-calendar-check me-1\"></i>Appointment\r\n");
      out.write("					</a></li>\r\n");
      out.write("					<li class=\"nav-item me-4\"><a class=\"nav-link\" href=\"User.jsp\">\r\n");
      out.write("							<i class=\"fa-solid fa-user me-1\"></i>User\r\n");
      out.write("					</a></li>\r\n");
      out.write("					<li class=\"nav-item me-4\"><a class=\"nav-link\"\r\n");
      out.write("						href=\"Doctor.jsp\"> <i class=\"fa-solid fa-user-doctor me-1\"></i>Doctor\r\n");
      out.write("					</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"> <i\r\n");
      out.write("							class=\"fa-solid fa-user-circle\"></i>\r\n");
      out.write("					</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Main Content -->\r\n");
      out.write("    <div class=\"main-content\">\r\n");
      out.write("        <div class=\"welcome-card\">\r\n");
      out.write("            <h1>Welcome to MediBridge</h1>\r\n");
      out.write("            <p>To book an appointment please sign up for a new account or sign in to your existing account.</p>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"auth-buttons\">\r\n");
      out.write("                <a href=\"User.jsp\" class=\"btn btn-primary\">Sign In</a>\r\n");
      out.write("                <a href=\"Signup.jsp\" class=\"btn btn-secondary\">Create New Account</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
