/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-08-27 19:58:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.User;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.DAO.DoctorDao;
import com.db.DBConnect;
import com.entity.Doctor_entity;
import java.util.List;

public final class User_005findex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/components/cdn-links.jsp", Long.valueOf(1753218954008L));
    _jspx_dependants.put("/components/navbar.jsp", Long.valueOf(1756324693024L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1749728082234L));
    _jspx_dependants.put("jar:file:/D:/Abhinav_Eclipse/Hospital_Management_System/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Hospital_Management_System/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.entity.Doctor_entity");
    _jspx_imports_classes.add("com.db.DBConnect");
    _jspx_imports_classes.add("com.DAO.DoctorDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Book Appointment - MediBridge</title>\r\n");
      out.write("<!-- Include CDN links -->\r\n");
      out.write("<!-- CDN Links File - Include this in your HTML files -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS should come first -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS should come at the end, before closing </body> or in <head> -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery (optional, if needed) -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Popper.js (optional, if using Bootstrap tooltips/popovers separately) -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.8/umd/popper.min.js\"></script>");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        background: linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%);\r\n");
      out.write("        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("        min-height: 100vh;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .page-header {\r\n");
      out.write("        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("        color: white;\r\n");
      out.write("        padding: 2.5rem 0;\r\n");
      out.write("        box-shadow: 0 4px 20px rgba(0,0,0,0.15);\r\n");
      out.write("        position: relative;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .page-header::before {\r\n");
      out.write("        content: '';\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        right: 0;\r\n");
      out.write("        bottom: 0;\r\n");
      out.write("        background: url('data:image/svg+xml,<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 100 100\"><defs><pattern id=\"grid\" width=\"10\" height=\"10\" patternUnits=\"userSpaceOnUse\"><path d=\"M 10 0 L 0 0 0 10\" fill=\"none\" stroke=\"rgba(255,255,255,0.1)\" stroke-width=\"1\"/></pattern></defs><rect width=\"100\" height=\"100\" fill=\"url(%23grid)\"/></svg>');\r\n");
      out.write("        opacity: 0.5;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .page-header .container {\r\n");
      out.write("        position: relative;\r\n");
      out.write("        z-index: 2;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .page-header h1 {\r\n");
      out.write("        font-size: 2.5rem;\r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        gap: 15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .page-header .fa-calendar-plus {\r\n");
      out.write("        color: #a8d8ff;\r\n");
      out.write("        font-size: 2.2rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .page-header p {\r\n");
      out.write("        font-size: 1.1rem;\r\n");
      out.write("        opacity: 0.9;\r\n");
      out.write("        font-weight: 300;\r\n");
      out.write("        margin: 8px 0 0 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .main-content {\r\n");
      out.write("        padding: 3rem 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .appointment-card {\r\n");
      out.write("        background: white;\r\n");
      out.write("        border-radius: 25px;\r\n");
      out.write("        box-shadow: 0 15px 50px rgba(0,0,0,0.1);\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("        position: relative;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .appointment-card::before {\r\n");
      out.write("        content: '';\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        right: 0;\r\n");
      out.write("        height: 5px;\r\n");
      out.write("        background: linear-gradient(90deg, #667eea, #764ba2, #f093fb, #4facfe);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card-header {\r\n");
      out.write("        background: linear-gradient(135deg, rgba(102, 126, 234, 0.05) 0%, rgba(118, 75, 162, 0.05) 100%);\r\n");
      out.write("        padding: 2rem 2.5rem 1rem 2.5rem;\r\n");
      out.write("        border-bottom: 1px solid #e9ecef;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card-header h3 {\r\n");
      out.write("        font-size: 1.8rem;\r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("        color: #333;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        gap: 12px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card-header .fa-user-plus {\r\n");
      out.write("        color: #667eea;\r\n");
      out.write("        font-size: 1.5rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card-body {\r\n");
      out.write("        padding: 2.5rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-section {\r\n");
      out.write("        margin-bottom: 2.5rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-section:last-child {\r\n");
      out.write("        margin-bottom: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .section-title {\r\n");
      out.write("        font-size: 1.2rem;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        color: #495057;\r\n");
      out.write("        margin-bottom: 1.5rem;\r\n");
      out.write("        padding-bottom: 0.5rem;\r\n");
      out.write("        border-bottom: 2px solid #e9ecef;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        gap: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .section-title i {\r\n");
      out.write("        color: #667eea;\r\n");
      out.write("        font-size: 1.1rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-group {\r\n");
      out.write("        margin-bottom: 1.5rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-label {\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        color: #495057;\r\n");
      out.write("        margin-bottom: 0.5rem;\r\n");
      out.write("        font-size: 0.95rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-control, .form-select {\r\n");
      out.write("        border: 2px solid #e9ecef;\r\n");
      out.write("        border-radius: 12px;\r\n");
      out.write("        padding: 12px 15px;\r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("        transition: all 0.3s ease;\r\n");
      out.write("        background: #fafbfc;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-control:focus, .form-select:focus {\r\n");
      out.write("        border-color: #667eea;\r\n");
      out.write("        box-shadow: 0 0 0 0.2rem rgba(102, 126, 234, 0.15);\r\n");
      out.write("        background: white;\r\n");
      out.write("        outline: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-control:hover, .form-select:hover {\r\n");
      out.write("        border-color: #ced4da;\r\n");
      out.write("        background: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .input-group-text {\r\n");
      out.write("        background: transparent;\r\n");
      out.write("        color: #667eea;\r\n");
      out.write("        border: 2px solid #e9ecef;\r\n");
      out.write("        border-right: none;\r\n");
      out.write("        border-radius: 12px 0 0 12px;\r\n");
      out.write("        padding: 12px 15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .input-group .form-control {\r\n");
      out.write("        border-radius: 0 12px 12px 0;\r\n");
      out.write("        border-left: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .input-group .form-control:focus {\r\n");
      out.write("        border-left: none;\r\n");
      out.write("        border-color: #667eea;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .submit-section {\r\n");
      out.write("        background: linear-gradient(135deg, rgba(102, 126, 234, 0.05) 0%, rgba(118, 75, 162, 0.05) 100%);\r\n");
      out.write("        padding: 2rem 2.5rem;\r\n");
      out.write("        margin: 0 -2.5rem -2.5rem -2.5rem;\r\n");
      out.write("        border-top: 1px solid #e9ecef;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-submit {\r\n");
      out.write("        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 50px;\r\n");
      out.write("        padding: 15px 50px;\r\n");
      out.write("        font-size: 1.1rem;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        color: white;\r\n");
      out.write("        transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);\r\n");
      out.write("        box-shadow: 0 5px 20px rgba(102, 126, 234, 0.3);\r\n");
      out.write("        position: relative;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("        min-width: 250px;\r\n");
      out.write("        display: inline-flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        gap: 8px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-submit::before {\r\n");
      out.write("        content: '';\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        left: -100%;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.2), transparent);\r\n");
      out.write("        transition: left 0.5s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-submit:hover::before {\r\n");
      out.write("        left: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-submit:hover {\r\n");
      out.write("        transform: translateY(-2px);\r\n");
      out.write("        box-shadow: 0 8px 30px rgba(102, 126, 234, 0.4);\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-submit:active {\r\n");
      out.write("        transform: translateY(0);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-reset {\r\n");
      out.write("        display: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .required {\r\n");
      out.write("        color: #dc3545;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-text {\r\n");
      out.write("        font-size: 0.85rem;\r\n");
      out.write("        color: #6c757d;\r\n");
      out.write("        margin-top: 0.25rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .doctor-avatar {\r\n");
      out.write("        width: 40px;\r\n");
      out.write("        height: 40px;\r\n");
      out.write("        border-radius: 50%;\r\n");
      out.write("        background: linear-gradient(135deg, #667eea, #764ba2);\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-size: 0.9rem;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        margin-right: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("        .page-header h1 {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .page-header .fa-calendar-plus {\r\n");
      out.write("            font-size: 1.8rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .card-header, .card-body, .submit-section {\r\n");
      out.write("            padding: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .submit-section {\r\n");
      out.write("            margin: 0 -1.5rem -1.5rem -1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-submit, .btn-reset {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            margin: 0.5rem 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .main-content {\r\n");
      out.write("            padding: 2rem 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .appointment-card {\r\n");
      out.write("            margin: 0 1rem;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 576px) {\r\n");
      out.write("        .page-header h1 {\r\n");
      out.write("            font-size: 1.8rem;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .card-header h3 {\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            gap: 8px;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Include Navbar -->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Fixed Navbar</title>\r\n");
      out.write("<!-- Include CDN links from external file -->\r\n");
      out.write("<!-- CDN Links File - Include this in your HTML files -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS should come first -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS should come at the end, before closing </body> or in <head> -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery (optional, if needed) -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Popper.js (optional, if using Bootstrap tooltips/popovers separately) -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.8/umd/popper.min.js\"></script>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark border-bottom\">\r\n");
      out.write("		<div class=\"container-fluid\">\r\n");
      out.write("			<a class=\"navbar-brand\" href=\"index.jsp\"> <img\r\n");
      out.write("				src=\"assets/logo.png\" alt=\"Logo\" width=\"35\" height=\"40\"\r\n");
      out.write("				class=\"d-inline-block align-text-top me-2 rounded-circle\"\r\n");
      out.write("				onerror=\"this.style.display='none'\"> MediBridge\r\n");
      out.write("			</a>\r\n");
      out.write("\r\n");
      out.write("			<!-- Navbar toggler for mobile -->\r\n");
      out.write("			<button class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("				data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNavDropdown\"\r\n");
      out.write("				aria-controls=\"navbarNavDropdown\" aria-expanded=\"false\"\r\n");
      out.write("				aria-label=\"Toggle navigation\">\r\n");
      out.write("				<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("			</button>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"navbarNavDropdown\">\r\n");
      out.write("				<ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("					<li class=\"nav-item me-4\"><a class=\"nav-link active\"\r\n");
      out.write("						aria-current=\"page\" href=\"Admin.jsp\"> <i\r\n");
      out.write("							class=\"fa-solid fa-user-shield me-1\"></i>Admin\r\n");
      out.write("					</a></li>\r\n");
      out.write("					<li class=\"nav-item me-4\"><a class=\"nav-link\"\r\n");
      out.write("						href=\"User/User_index.jsp\"> <i\r\n");
      out.write("							class=\"fa-solid fa-calendar-check me-1\"></i>Appointment\r\n");
      out.write("					</a></li>\r\n");
      out.write("					<li class=\"nav-item me-4\"><a class=\"nav-link\" href=\"User.jsp\">\r\n");
      out.write("							<i class=\"fa-solid fa-user me-1\"></i>User\r\n");
      out.write("					</a></li>\r\n");
      out.write("					<li class=\"nav-item me-4\"><a class=\"nav-link\"\r\n");
      out.write("						href=\"Doctor.jsp\"> <i class=\"fa-solid fa-user-doctor me-1\"></i>Doctor\r\n");
      out.write("					</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"> <i\r\n");
      out.write("							class=\"fa-solid fa-user-circle\"></i>\r\n");
      out.write("					</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Page Header -->\r\n");
      out.write("<div class=\"page-header\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row align-items-center\">\r\n");
      out.write("            <div class=\"col\">\r\n");
      out.write("                <h1>\r\n");
      out.write("                    <i class=\"fas fa-calendar-plus\"></i>\r\n");
      out.write("                    Book Appointment\r\n");
      out.write("                </h1>\r\n");
      out.write("                <p>Schedule your medical consultation with our expert doctors</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Main Content -->\r\n");
      out.write("<div class=\"main-content\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row justify-content-center\">\r\n");
      out.write("            <div class=\"col-lg-8 col-xl-7\">\r\n");
      out.write("                <div class=\"card appointment-card\">\r\n");
      out.write("                    <div class=\"card-header\">\r\n");
      out.write("                        <h3>\r\n");
      out.write("                            <i class=\"fas fa-user-plus\"></i>\r\n");
      out.write("                            Patient Information\r\n");
      out.write("                        </h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <form action=\"bookAppointment\" method=\"post\" id=\"appointmentForm\">\r\n");
      out.write("                            \r\n");
      out.write("                            <input type=\"hidden\" name=\"userid\" value=\"${userObj.name}\">\r\n");
      out.write("                            <!-- Personal Information Section -->\r\n");
      out.write("                            <div class=\"form-section\">\r\n");
      out.write("                                <h4 class=\"section-title\">\r\n");
      out.write("                                    <i class=\"fas fa-user\"></i>\r\n");
      out.write("                                    Personal Details\r\n");
      out.write("                                </h4>\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-md-8\">\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <label for=\"fullName\" class=\"form-label\">Full Name <span class=\"required\">*</span></label>\r\n");
      out.write("                                            <div class=\"input-group\">\r\n");
      out.write("                                                <span class=\"input-group-text\">\r\n");
      out.write("                                                    <i class=\"fas fa-user\"></i>\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                                <input type=\"text\" class=\"form-control\" id=\"fullName\" name=\"fullName\" \r\n");
      out.write("                                                       placeholder=\"Enter your full name\" required>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-4\">\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <label for=\"gender\" class=\"form-label\">Gender <span class=\"required\">*</span></label>\r\n");
      out.write("                                            <select class=\"form-select\" id=\"gender\" name=\"gender\" required>\r\n");
      out.write("                                                <option value=\"\">Select Gender</option>\r\n");
      out.write("                                                <option value=\"Male\">Male</option>\r\n");
      out.write("                                                <option value=\"Female\">Female</option>\r\n");
      out.write("                                                <option value=\"Other\">Other</option>\r\n");
      out.write("                                            </select>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <label for=\"age\" class=\"form-label\">Age <span class=\"required\">*</span></label>\r\n");
      out.write("                                            <div class=\"input-group\">\r\n");
      out.write("                                                <span class=\"input-group-text\">\r\n");
      out.write("                                                    <i class=\"fas fa-birthday-cake\"></i>\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                                <input type=\"number\" class=\"form-control\" id=\"age\" name=\"age\" \r\n");
      out.write("                                                       placeholder=\"Enter age\" min=\"1\" max=\"120\" required>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <label for=\"appointmentDate\" class=\"form-label\">Appointment Date <span class=\"required\">*</span></label>\r\n");
      out.write("                                            <div class=\"input-group\">\r\n");
      out.write("                                                <span class=\"input-group-text\">\r\n");
      out.write("                                                    <i class=\"fas fa-calendar-alt\"></i>\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                                <input type=\"date\" class=\"form-control\" id=\"appointmentDate\" name=\"appointmentDate\" \r\n");
      out.write("                                                       min=\"");
      out.print( new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date()) );
      out.write("\" required>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Contact Information Section -->\r\n");
      out.write("                            <div class=\"form-section\">\r\n");
      out.write("                                <h4 class=\"section-title\">\r\n");
      out.write("                                    <i class=\"fas fa-address-book\"></i>\r\n");
      out.write("                                    Contact Information\r\n");
      out.write("                                </h4>\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <label for=\"email\" class=\"form-label\">Email Address <span class=\"required\">*</span></label>\r\n");
      out.write("                                            <div class=\"input-group\">\r\n");
      out.write("                                                <span class=\"input-group-text\">\r\n");
      out.write("                                                    <i class=\"fas fa-envelope\"></i>\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                                <input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" \r\n");
      out.write("                                                       placeholder=\"Enter email address\" required>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <label for=\"phoneNo\" class=\"form-label\">Phone Number <span class=\"required\">*</span></label>\r\n");
      out.write("                                            <div class=\"input-group\">\r\n");
      out.write("                                                <span class=\"input-group-text\">\r\n");
      out.write("                                                    <i class=\"fas fa-phone\"></i>\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                                <input type=\"tel\" class=\"form-control\" id=\"phoneNo\" name=\"phoneNo\" \r\n");
      out.write("                                                       placeholder=\"+91 XXXXXXXXXX\" pattern=\"[0-9]{10}\" required>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"form-text\">Please enter 10-digit mobile number</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Medical Information Section -->\r\n");
      out.write("                            <div class=\"form-section\">\r\n");
      out.write("                                <h4 class=\"section-title\">\r\n");
      out.write("                                    <i class=\"fas fa-heartbeat\"></i>\r\n");
      out.write("                                    Medical Information\r\n");
      out.write("                                </h4>\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <label for=\"diseases\" class=\"form-label\">Medical Condition</label>\r\n");
      out.write("                                            <div class=\"input-group\">\r\n");
      out.write("                                                <span class=\"input-group-text\">\r\n");
      out.write("                                                    <i class=\"fas fa-notes-medical\"></i>\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                                <input type=\"text\" class=\"form-control\" id=\"diseases\" name=\"diseases\" \r\n");
      out.write("                                                       placeholder=\"Describe your condition (optional)\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6\">\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <label for=\"doctor\" class=\"form-label\">Preferred Doctor</label>\r\n");
      out.write("                                            <select class=\"form-select\" id=\"doctor\" name=\"doctor\">\r\n");
      out.write("    <option value=\"\">Select Doctor (Optional)</option>\r\n");
      out.write("                                             ");

                                             DoctorDao dao = new DoctorDao(DBConnect.getConn());
                                             List<Doctor_entity> list = dao.getAllDoctor() ;
                                            		for(Doctor_entity d : list){
                                            		
      out.write("\r\n");
      out.write("                                            		<option value=\"");
      out.print(d.getId());
      out.write('"');
      out.write('>');
      out.print(d.getDoc_name());
      out.write(' ');
      out.write('(');
      out.print(d.getDoc_spec());
      out.write(")</option>\r\n");
      out.write("                                            		");
}
                                            		 
      out.write("\r\n");
      out.write("                                            </select>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Address Section -->\r\n");
      out.write("                            <div class=\"form-section\">\r\n");
      out.write("                                <h4 class=\"section-title\">\r\n");
      out.write("                                    <i class=\"fas fa-map-marker-alt\"></i>\r\n");
      out.write("                                    Address Information\r\n");
      out.write("                                </h4>\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <label for=\"fullAddress\" class=\"form-label\">Full Address <span class=\"required\">*</span></label>\r\n");
      out.write("                                    <div class=\"input-group\">\r\n");
      out.write("                                        <span class=\"input-group-text\">\r\n");
      out.write("                                            <i class=\"fas fa-home\"></i>\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                        <textarea class=\"form-control\" id=\"fullAddress\" name=\"fullAddress\" \r\n");
      out.write("                                                  placeholder=\"Enter your complete address including city, state, and PIN code\" \r\n");
      out.write("                                                  rows=\"3\" required></textarea>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-text\">Please include street address, city, state, and postal code</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- Submit Section -->\r\n");
      out.write("                    <div class=\"submit-section\">\r\n");
      out.write("                        <button type=\"submit\" form=\"appointmentForm\" class=\"btn btn-submit mb-8\">\r\n");
      out.write("                            <i class=\"fas fa-calendar-check\"></i>\r\n");
      out.write("                            Book Appointment\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("// Form validation and enhancement\r\n");
      out.write("document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("    const form = document.getElementById('appointmentForm');\r\n");
      out.write("    const phoneInput = document.getElementById('phoneNo');\r\n");
      out.write("    const dateInput = document.getElementById('appointmentDate');\r\n");
      out.write("    \r\n");
      out.write("    // Phone number formatting\r\n");
      out.write("    phoneInput.addEventListener('input', function(e) {\r\n");
      out.write("        let value = e.target.value.replace(/\\D/g, '');\r\n");
      out.write("        if (value.length > 10) {\r\n");
      out.write("            value = value.slice(0, 10);\r\n");
      out.write("        }\r\n");
      out.write("        e.target.value = value;\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    // Set minimum date to today\r\n");
      out.write("    const today = new Date().toISOString().split('T')[0];\r\n");
      out.write("    dateInput.min = today;\r\n");
      out.write("    \r\n");
      out.write("    // Form submission handling\r\n");
      out.write("    form.addEventListener('submit', function(e) {\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("        \r\n");
      out.write("        // Basic validation\r\n");
      out.write("        const requiredFields = form.querySelectorAll('[required]');\r\n");
      out.write("        let allValid = true;\r\n");
      out.write("        \r\n");
      out.write("        requiredFields.forEach(field => {\r\n");
      out.write("            if (!field.value.trim()) {\r\n");
      out.write("                allValid = false;\r\n");
      out.write("                field.classList.add('is-invalid');\r\n");
      out.write("            } else {\r\n");
      out.write("                field.classList.remove('is-invalid');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        if (allValid) {\r\n");
      out.write("            // Show loading state\r\n");
      out.write("            const submitBtn = form.querySelector('.btn-submit');\r\n");
      out.write("            const originalText = submitBtn.innerHTML;\r\n");
      out.write("            submitBtn.innerHTML = '<i class=\"fas fa-spinner fa-spin me-2\"></i>Booking...';\r\n");
      out.write("            submitBtn.disabled = true;\r\n");
      out.write("            \r\n");
      out.write("            // Simulate form submission (replace with actual submission)\r\n");
      out.write("            setTimeout(() => {\r\n");
      out.write("                alert('Appointment booked successfully!');\r\n");
      out.write("                submitBtn.innerHTML = originalText;\r\n");
      out.write("                submitBtn.disabled = false;\r\n");
      out.write("                // form.submit(); // Uncomment for actual submission\r\n");
      out.write("            }, 2000);\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    // Add focus effects\r\n");
      out.write("    const inputs = form.querySelectorAll('.form-control, .form-select');\r\n");
      out.write("    inputs.forEach(input => {\r\n");
      out.write("        input.addEventListener('focus', function() {\r\n");
      out.write("            this.parentElement.classList.add('focused');\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        input.addEventListener('blur', function() {\r\n");
      out.write("            this.parentElement.classList.remove('focused');\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
