/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-08-29 12:43:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.User;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.DAO.AppointmentDao;
import com.DAO.DoctorDao;
import com.db.DBConnect;
import com.entity.Appointment_entity;
import com.entity.User;
import com.entity.Doctor_entity;
import java.util.*;

public final class View_005fappointment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/components/cdn-links.jsp", Long.valueOf(1753218954008L));
    _jspx_dependants.put("/User/userlogin_navbar.jsp", Long.valueOf(1756407900312L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("com.DAO.AppointmentDao");
    _jspx_imports_classes.add("com.entity.Doctor_entity");
    _jspx_imports_classes.add("com.entity.User");
    _jspx_imports_classes.add("com.db.DBConnect");
    _jspx_imports_classes.add("com.DAO.DoctorDao");
    _jspx_imports_classes.add("com.entity.Appointment_entity");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>MediBridge : View Appointments</title>\r\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        background: linear-gradient(135deg, #e3f2fd 0%, #f5f5f5 100%);\r\n");
      out.write("        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .hero-section {\r\n");
      out.write("        background: linear-gradient(135deg, #2c5f7c 0%, #1e4a61 100%);\r\n");
      out.write("        height: 200px;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .hero-section::before {\r\n");
      out.write("        content: '';\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: -50%;\r\n");
      out.write("        right: -10%;\r\n");
      out.write("        width: 300px;\r\n");
      out.write("        height: 300px;\r\n");
      out.write("        background: rgba(52, 152, 219, 0.3);\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("        transform: rotate(45deg);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .hero-section::after {\r\n");
      out.write("        content: '';\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        bottom: -20%;\r\n");
      out.write("        right: 5%;\r\n");
      out.write("        width: 200px;\r\n");
      out.write("        height: 200px;\r\n");
      out.write("        background: rgba(52, 152, 219, 0.2);\r\n");
      out.write("        border-radius: 15px;\r\n");
      out.write("        transform: rotate(30deg);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .main-container {\r\n");
      out.write("        margin-top: -80px;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        z-index: 10;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .appointment-card {\r\n");
      out.write("        background: white;\r\n");
      out.write("        border-radius: 15px;\r\n");
      out.write("        box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        padding: 30px;\r\n");
      out.write("        margin-bottom: 30px;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .appointment-card::before {\r\n");
      out.write("        content: '';\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        right: 0;\r\n");
      out.write("        height: 4px;\r\n");
      out.write("        background: linear-gradient(90deg, #28a745, #20c997, #17a2b8);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .card-title {\r\n");
      out.write("        color: #28a745;\r\n");
      out.write("        font-size: 2rem;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        margin-bottom: 40px;\r\n");
      out.write("        position: relative;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .card-title::after {\r\n");
      out.write("        content: '';\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        bottom: -10px;\r\n");
      out.write("        left: 50%;\r\n");
      out.write("        transform: translateX(-50%);\r\n");
      out.write("        width: 80px;\r\n");
      out.write("        height: 3px;\r\n");
      out.write("        background: linear-gradient(90deg, #28a745, #20c997);\r\n");
      out.write("        border-radius: 2px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .table-responsive {\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("        box-shadow: 0 5px 15px rgba(0, 0, 0, 0.08);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .custom-table {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        background: white;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .custom-table thead {\r\n");
      out.write("        background: linear-gradient(135deg, #28a745, #20c997);\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .custom-table th {\r\n");
      out.write("        border: none;\r\n");
      out.write("        padding: 15px 12px;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        font-size: 0.9rem;\r\n");
      out.write("        letter-spacing: 0.5px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .custom-table td {\r\n");
      out.write("        padding: 15px 12px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        vertical-align: middle;\r\n");
      out.write("        border-bottom: 1px solid #f1f3f4;\r\n");
      out.write("        font-size: 0.9rem;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .custom-table tbody tr {\r\n");
      out.write("        transition: all 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .custom-table tbody tr:hover {\r\n");
      out.write("        background-color: #f8f9fa;\r\n");
      out.write("        transform: translateY(-1px);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .status-badge {\r\n");
      out.write("        padding: 6px 12px;\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("        font-size: 0.8rem;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        text-transform: uppercase;\r\n");
      out.write("        letter-spacing: 0.5px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .status-ok {\r\n");
      out.write("        background-color: #d4edda;\r\n");
      out.write("        color: #155724;\r\n");
      out.write("        border: 1px solid #c3e6cb;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .status-pending {\r\n");
      out.write("        background-color: #fff3cd;\r\n");
      out.write("        color: #856404;\r\n");
      out.write("        border: 1px solid #ffeaa7;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .doctor-image-section {\r\n");
      out.write("        position: relative;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .doctor-image {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        max-width: 300px;\r\n");
      out.write("        height: auto;\r\n");
      out.write("        border-radius: 15px;\r\n");
      out.write("        box-shadow: 0 10px 25px rgba(0, 0, 0, 0.15);\r\n");
      out.write("        transition: transform 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .doctor-image:hover {\r\n");
      out.write("        transform: translateY(-5px);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .floating-elements {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 20px;\r\n");
      out.write("        right: 20px;\r\n");
      out.write("        opacity: 0.1;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .floating-elements i {\r\n");
      out.write("        font-size: 2rem;\r\n");
      out.write("        color: #28a745;\r\n");
      out.write("        margin: 0 10px;\r\n");
      out.write("        animation: float 3s ease-in-out infinite;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .floating-elements i:nth-child(2) {\r\n");
      out.write("        animation-delay: 1s;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .floating-elements i:nth-child(3) {\r\n");
      out.write("        animation-delay: 2s;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    @keyframes float {\r\n");
      out.write("        0%, 100% { transform: translateY(0px); }\r\n");
      out.write("        50% { transform: translateY(-10px); }\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .stats-card {\r\n");
      out.write("        background: linear-gradient(135deg, #28a745, #20c997);\r\n");
      out.write("        color: white;\r\n");
      out.write("        border-radius: 15px;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        box-shadow: 0 5px 15px rgba(40, 167, 69, 0.3);\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .stats-number {\r\n");
      out.write("        font-size: 2.5rem;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        margin-bottom: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .stats-label {\r\n");
      out.write("        font-size: 0.9rem;\r\n");
      out.write("        opacity: 0.9;\r\n");
      out.write("        text-transform: uppercase;\r\n");
      out.write("        letter-spacing: 1px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .no-appointments {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        padding: 40px 20px;\r\n");
      out.write("        color: #6c757d;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .no-appointments i {\r\n");
      out.write("        font-size: 3rem;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("        color: #dee2e6;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("        .appointment-card {\r\n");
      out.write("            margin: 15px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .custom-table th,\r\n");
      out.write("        .custom-table td {\r\n");
      out.write("            padding: 10px 8px;\r\n");
      out.write("            font-size: 0.8rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .card-title {\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .doctor-image {\r\n");
      out.write("            max-width: 250px;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>MediBridge: User</title>\r\n");
      out.write("\r\n");
      out.write("<!-- CDN Links File - Include this in your HTML files -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS should come first -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS should come at the end, before closing </body> or in <head> -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery (optional, if needed) -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Popper.js (optional, if using Bootstrap tooltips/popovers separately) -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.8/umd/popper.min.js\"></script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	background-color: #f8f9fa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-brand {\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	_\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-link {\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("	transition: color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-link:hover {\r\n");
      out.write("	color: #ffc107 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-menu {\r\n");
      out.write("	border: none;\r\n");
      out.write("	box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-item:hover {\r\n");
      out.write("	background-color: #f8f9fa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content-area {\r\n");
      out.write("	margin-top: 2rem;\r\n");
      out.write("	padding: 2rem;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- to solve the issue of back button accessing the admin page you should remove the cache  -->\r\n");
      out.write("	");

	response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");

	if (session.getAttribute("userObj") == null) {
		response.sendRedirect("../User/user_index.jsp");
	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark border-bottom\">\r\n");
      out.write("		<div class=\"container-fluid\">\r\n");
      out.write("			<a class=\"navbar-brand\" href=\"index.jsp\"> <img\r\n");
      out.write("				src=\"../assets/logo.png\" alt=\"Logo\" width=\"35\" height=\"40\"\r\n");
      out.write("				class=\"d-inline-block align-text-top me-2 rounded-circle\"\r\n");
      out.write("				onerror=\"this.style.display='none'\"> MediBridge\r\n");
      out.write("			</a>\r\n");
      out.write("\r\n");
      out.write("			<!-- Navbar toggler for mobile -->\r\n");
      out.write("			<button class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("				data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNavDropdown\"\r\n");
      out.write("				aria-controls=\"navbarNavDropdown\" aria-expanded=\"false\"\r\n");
      out.write("				aria-label=\"Toggle navigation\">\r\n");
      out.write("				<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("			</button>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"navbarNavDropdown\">\r\n");
      out.write("				<ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("					<li class=\"nav-item me-4\"><a class=\"nav-link active\"\r\n");
      out.write("						aria-current=\"page\" href=\"../index.jsp\"> <i\r\n");
      out.write("							class=\"fa-solid fa-home me-1\"></i>Appointment\r\n");
      out.write("					</a></li>\r\n");
      out.write("\r\n");
      out.write("					<li class=\"nav-item me-4\"><a class=\"nav-link\"\r\n");
      out.write("						href=\"../User/View_appointment.jsp\"> <i class=\"fa-solid fa-user-doctor me-1\"></i>View\r\n");
      out.write("							Appointment\r\n");
      out.write("					</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<div class=\"dropdown\">\r\n");
      out.write("						<button class=\"btn btn-secondary dropdown-toggle\" type=\"button\"\r\n");
      out.write("							id=\"dropdownMenuButton\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("							aria-expanded=\"false\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userObj.fullname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</button>\r\n");
      out.write("						<ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuButton\">\r\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"#\">Change Password</a></li>\r\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"../user_logout\">Logout</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- Hero Section -->\r\n");
      out.write("    <div class=\"hero-section\">\r\n");
      out.write("        <div class=\"floating-elements\">\r\n");
      out.write("            <i class=\"fas fa-heartbeat\"></i>\r\n");
      out.write("            <i class=\"fas fa-user-md\"></i>\r\n");
      out.write("            <i class=\"fas fa-calendar-check\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Main Container -->\r\n");
      out.write("    <div class=\"container main-container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <!-- Appointment Table Section -->\r\n");
      out.write("            <div class=\"col-lg-8 col-md-12\">\r\n");
      out.write("                <div class=\"appointment-card\">\r\n");
      out.write("                    <h2 class=\"card-title\">\r\n");
      out.write("                        <i class=\"fas fa-calendar-alt me-2\"></i>\r\n");
      out.write("                        Appointment List\r\n");
      out.write("                    </h2>\r\n");
      out.write("                    \r\n");
      out.write("                    ");

                        User user_id = (User)session.getAttribute("userObj");
                        if(user_id != null) {
                            AppointmentDao dao = new AppointmentDao(DBConnect.getConn());
                            DoctorDao dao2 = new DoctorDao(DBConnect.getConn());
                            List<Appointment_entity> list = dao.getAllApointmentById(user_id.getId());
                            
                            if(list != null && !list.isEmpty()) {
                    
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"table-responsive\">\r\n");
      out.write("                        <table class=\"table custom-table\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>Full Name</th>\r\n");
      out.write("                                    <th>Gender</th>\r\n");
      out.write("                                    <th>Age</th>\r\n");
      out.write("                                    <th>Appoint Date</th>\r\n");
      out.write("                                    <th>Diseases</th>\r\n");
      out.write("                                    <th>Doctor Name</th>\r\n");
      out.write("                                    <th>Status</th>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                                ");

                                    int totalAppointments = list.size();
                                    int completedAppointments = 0;
                                    
                                    for(Appointment_entity ap : list){
                                    	Doctor_entity d = dao2.getDoctorDetails(ap.getDoct_id());                                        if("Completed".equals(ap.getApp_status())) {
                                            completedAppointments++;
                                        }
                                
      out.write("\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td><strong>");
      out.print(ap.getApp_name());
      out.write("</strong></td>\r\n");
      out.write("                                    <td>");
      out.print(ap.getApp_gender());
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print(ap.getApp_age());
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print(ap.getApp_date());
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print(ap.getApp_cond());
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print(d != null ? d.getDoc_name() : "N/A");
      out.write("</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        ");

                                        if ("Pending".equals(ap.getApp_status())) {
                                        
      out.write("\r\n");
      out.write("                                            <span class=\"status-badge status-pending\">Pending</span>\r\n");
      out.write("                                        ");

                                        } else if("Completed".equals(ap.getApp_status())){
                                        
      out.write("\r\n");
      out.write("                                            <span class=\"status-badge status-ok\">Completed</span>\r\n");
      out.write("                                        ");

                                        } else {
                                        
      out.write("\r\n");
      out.write("                                            <span class=\"status-badge status-ok\">");
      out.print(ap.getApp_status());
      out.write("</span>\r\n");
      out.write("                                        ");

                                        }
                                        
      out.write("\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                ");

                                    }
                                
      out.write("\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    ");

                        } else {
                    
      out.write("\r\n");
      out.write("                    <div class=\"no-appointments\">\r\n");
      out.write("                        <i class=\"fas fa-calendar-times\"></i>\r\n");
      out.write("                        <h4>No Appointments Found</h4>\r\n");
      out.write("                        <p>You haven't booked any appointments yet.</p>\r\n");
      out.write("                        <a href=\"../User/User_index.jsp\" class=\"btn btn-success\">Book Your First Appointment</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");

                        }
                    } else {
                    
      out.write("\r\n");
      out.write("                    <div class=\"no-appointments\">\r\n");
      out.write("                        <i class=\"fas fa-user-times\"></i>\r\n");
      out.write("                        <h4>Please Login</h4>\r\n");
      out.write("                        <p>You need to login to view your appointments.</p>\r\n");
      out.write("                        <a href=\"../User/user_login.jsp\" class=\"btn btn-primary\">Login Now</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");

                    }
                    
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Doctor Image and Stats Section -->\r\n");
      out.write("            <div class=\"col-lg-4 col-md-12\">\r\n");
      out.write("                <div class=\"doctor-image-section text-center mb-4\">\r\n");
      out.write("                    <img src=\"https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80\" \r\n");
      out.write("                         alt=\"Doctor\" class=\"doctor-image\">\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                ");

                    User statsUser = (User)session.getAttribute("userObj");
                    if(statsUser != null) {
                        AppointmentDao statsDao = new AppointmentDao(DBConnect.getConn());
                        List<Appointment_entity> statsList = statsDao.getAllApointmentById(statsUser.getId());
                        int totalCount = statsList != null ? statsList.size() : 0;
                        int completedCount = 0;
                        
                        if(statsList != null) {
                            for(Appointment_entity ap : statsList) {
                                if("Completed".equals(ap.getApp_status())) {
                                    completedCount++;
                                }
                            }
                        }
                
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"stats-card\">\r\n");
      out.write("                    <div class=\"stats-number\">");
      out.print(totalCount);
      out.write("</div>\r\n");
      out.write("                    <div class=\"stats-label\">Total Appointments</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"stats-card\" style=\"background: linear-gradient(135deg, #17a2b8, #20c997);\">\r\n");
      out.write("                    <div class=\"stats-number\">");
      out.print(completedCount);
      out.write("</div>\r\n");
      out.write("                    <div class=\"stats-label\">Completed</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                ");

                    } else {
                
      out.write("\r\n");
      out.write("                <div class=\"stats-card\">\r\n");
      out.write("                    <div class=\"stats-number\">0</div>\r\n");
      out.write("                    <div class=\"stats-label\">Total Appointments</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"stats-card\" style=\"background: linear-gradient(135deg, #17a2b8, #20c997);\">\r\n");
      out.write("                    <div class=\"stats-number\">0</div>\r\n");
      out.write("                    <div class=\"stats-label\">Completed</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");

                    }
                
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
