/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-08-30 14:15:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.DAO.AppointmentDao;
import com.DAO.DoctorDao;
import com.db.DBConnect;
import com.entity.Appointment_entity;
import com.entity.Doctor_entity;
import java.util.*;

public final class admin_005fpatients_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/components/cdn-links.jsp", Long.valueOf(1753218954008L));
    _jspx_dependants.put("/admin/navbar.jsp", Long.valueOf(1756552074642L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("com.DAO.AppointmentDao");
    _jspx_imports_classes.add("com.entity.Doctor_entity");
    _jspx_imports_classes.add("com.db.DBConnect");
    _jspx_imports_classes.add("com.DAO.DoctorDao");
    _jspx_imports_classes.add("com.entity.Appointment_entity");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>MediBridge : Admin Patients</title>\r\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        background: linear-gradient(135deg, #e3f2fd 0%, #f8f9fa 100%);\r\n");
      out.write("        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("        min-height: 100vh;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .main-container {\r\n");
      out.write("        padding: 20px 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .page-header {\r\n");
      out.write("        background: linear-gradient(135deg, #2c5f7c 0%, #1e4a61 100%);\r\n");
      out.write("        color: white;\r\n");
      out.write("        padding: 40px 0;\r\n");
      out.write("        margin-bottom: 30px;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .page-header::before {\r\n");
      out.write("        content: '';\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: -50%;\r\n");
      out.write("        right: -10%;\r\n");
      out.write("        width: 300px;\r\n");
      out.write("        height: 300px;\r\n");
      out.write("        background: rgba(52, 152, 219, 0.2);\r\n");
      out.write("        border-radius: 50%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .page-title {\r\n");
      out.write("        font-size: 2.5rem;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        z-index: 2;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .page-subtitle {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        margin-top: 10px;\r\n");
      out.write("        opacity: 0.9;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        z-index: 2;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .appointments-card {\r\n");
      out.write("        background: white;\r\n");
      out.write("        border-radius: 15px;\r\n");
      out.write("        box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("        margin-bottom: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card-header {\r\n");
      out.write("        background: linear-gradient(135deg, #28a745, #20c997);\r\n");
      out.write("        color: white;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        border: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card-body {\r\n");
      out.write("        padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .table-responsive {\r\n");
      out.write("        border-radius: 0 0 15px 15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .custom-table {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        background: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .custom-table thead th {\r\n");
      out.write("        background: linear-gradient(135deg, #343a40, #495057);\r\n");
      out.write("        color: white;\r\n");
      out.write("        border: none;\r\n");
      out.write("        padding: 15px 10px;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        font-size: 0.85rem;\r\n");
      out.write("        letter-spacing: 0.5px;\r\n");
      out.write("        white-space: nowrap;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .custom-table tbody td {\r\n");
      out.write("        padding: 12px 10px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        vertical-align: middle;\r\n");
      out.write("        border-bottom: 1px solid #f1f3f4;\r\n");
      out.write("        font-size: 0.85rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .custom-table tbody tr {\r\n");
      out.write("        transition: all 0.2s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .custom-table tbody tr:hover {\r\n");
      out.write("        background-color: #f8f9fa;\r\n");
      out.write("        transform: translateY(-1px);\r\n");
      out.write("        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .status-badge {\r\n");
      out.write("        padding: 5px 10px;\r\n");
      out.write("        border-radius: 15px;\r\n");
      out.write("        font-size: 0.75rem;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        text-transform: uppercase;\r\n");
      out.write("        letter-spacing: 0.5px;\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .status-pending {\r\n");
      out.write("        background-color: #fff3cd;\r\n");
      out.write("        color: #856404;\r\n");
      out.write("        border: 1px solid #ffeaa7;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .status-completed {\r\n");
      out.write("        background-color: #d4edda;\r\n");
      out.write("        color: #155724;\r\n");
      out.write("        border: 1px solid #c3e6cb;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .status-cancelled {\r\n");
      out.write("        background-color: #f8d7da;\r\n");
      out.write("        color: #721c24;\r\n");
      out.write("        border: 1px solid #f5c6cb;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .patient-name {\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        color: #2c5f7c;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .doctor-name {\r\n");
      out.write("        color: #28a745;\r\n");
      out.write("        font-weight: 500;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .stats-row {\r\n");
      out.write("        margin-bottom: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .stat-card {\r\n");
      out.write("        background: white;\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        box-shadow: 0 5px 15px rgba(0, 0, 0, 0.08);\r\n");
      out.write("        border-left: 4px solid;\r\n");
      out.write("        transition: transform 0.2s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .stat-card:hover {\r\n");
      out.write("        transform: translateY(-3px);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .stat-card.total {\r\n");
      out.write("        border-left-color: #007bff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .stat-card.completed {\r\n");
      out.write("        border-left-color: #28a745;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .stat-card.pending {\r\n");
      out.write("        border-left-color: #ffc107;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .stat-card.cancelled {\r\n");
      out.write("        border-left-color: #dc3545;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .stat-number {\r\n");
      out.write("        font-size: 2rem;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        margin-bottom: 5px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .stat-label {\r\n");
      out.write("        color: #6c757d;\r\n");
      out.write("        font-size: 0.9rem;\r\n");
      out.write("        text-transform: uppercase;\r\n");
      out.write("        letter-spacing: 0.5px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .search-section {\r\n");
      out.write("        background: white;\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.05);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-export {\r\n");
      out.write("        background: linear-gradient(135deg, #6f42c1, #563d7c);\r\n");
      out.write("        border: none;\r\n");
      out.write("        color: white;\r\n");
      out.write("        border-radius: 25px;\r\n");
      out.write("        padding: 10px 20px;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-export:hover {\r\n");
      out.write("        transform: translateY(-2px);\r\n");
      out.write("        box-shadow: 0 5px 15px rgba(111, 66, 193, 0.4);\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("        .custom-table {\r\n");
      out.write("            font-size: 0.75rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .custom-table th,\r\n");
      out.write("        .custom-table td {\r\n");
      out.write("            padding: 8px 5px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .page-title {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .stat-card {\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>MediBridge: Administrator</title>\r\n");
      out.write("    \r\n");
      out.write("   ");
      out.write("<!-- CDN Links File - Include this in your HTML files -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS should come first -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS should come at the end, before closing </body> or in <head> -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery (optional, if needed) -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Popper.js (optional, if using Bootstrap tooltips/popovers separately) -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.8/umd/popper.min.js\"></script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            background-color: #f8f9fa;\r\n");
      out.write("        }\r\n");
      out.write("        .navbar-brand {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-link {\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            transition: color 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-link:hover {\r\n");
      out.write("            color: #ffc107 !important;\r\n");
      out.write("        }\r\n");
      out.write("        .dropdown-menu {\r\n");
      out.write("            border: none;\r\n");
      out.write("            box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15);\r\n");
      out.write("        }\r\n");
      out.write("        .dropdown-item:hover {\r\n");
      out.write("            background-color: #f8f9fa;\r\n");
      out.write("        }\r\n");
      out.write("        .content-area {\r\n");
      out.write("            margin-top: 2rem;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- to solve the issue of back button accessing the admin page you should remove the cache  -->\r\n");

response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");

if(session.getAttribute("adminObj") == null){
	response.sendRedirect("../Admin.jsp");
}


      out.write("   \r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark border-bottom\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"index.jsp\">\r\n");
      out.write("            <img src=\"../assets/logo.png\" alt=\"Logo\" width=\"35\" height=\"40\" \r\n");
      out.write("                 class=\"d-inline-block align-text-top me-2 rounded-circle\"\r\n");
      out.write("                 onerror=\"this.style.display='none'\">\r\n");
      out.write("            MediBridge\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <!-- Navbar toggler for mobile -->\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" \r\n");
      out.write("                data-bs-target=\"#navbarNavDropdown\" aria-controls=\"navbarNavDropdown\" \r\n");
      out.write("                aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarNavDropdown\">\r\n");
      out.write("            <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("                <li class=\"nav-item me-4\">\r\n");
      out.write("                    <a class=\"nav-link active\" aria-current=\"page\" href=\"index.jsp\">\r\n");
      out.write("                        <i class=\"fa-solid fa-home me-1\"></i>Home\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("                <li class=\"nav-item me-4\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"doctor_dashboard.jsp\">\r\n");
      out.write("                        <i class=\"fa-solid fa-user-doctor me-1\"></i>Doctor\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("                <li class=\"nav-item me-4\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"admin_patients.jsp\">\r\n");
      out.write("                        <i class=\"fa-solid fa-user-injured me-1\"></i>Patient\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                 \r\n");
      out.write("                <li class=\"nav-item me-4\">\r\n");
      out.write("                     <a class=\"nav-link\" href=\"../adminlogout\">\r\n");
      out.write("                         <i class=\"fa-solid fa-sign-out-alt me-2\"></i>Logout\r\n");
      out.write("                    </a>\r\n");
      out.write("               </li>       \r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Page Header -->\r\n");
      out.write("<div class=\"page-header\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h1 class=\"page-title\">\r\n");
      out.write("            <i class=\"fas fa-users-cog me-3\"></i>\r\n");
      out.write("            Patients Management\r\n");
      out.write("        </h1>\r\n");
      out.write("        <p class=\"page-subtitle\">\r\n");
      out.write("            <i class=\"fas fa-calendar-check me-2\"></i>\r\n");
      out.write("            Comprehensive view of all appointments and patient records\r\n");
      out.write("        </p>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container main-container\">\r\n");
      out.write("    <!-- Appointments Table -->\r\n");
      out.write("    <div class=\"appointments-card\">\r\n");
      out.write("        <div class=\"card-header\">\r\n");
      out.write("            <h4 class=\"mb-0\">\r\n");
      out.write("                <i class=\"fas fa-table me-2\"></i>\r\n");
      out.write("                All Appointments\r\n");
      out.write("            </h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("            <div class=\"table-responsive\">\r\n");
      out.write("                <table class=\"table custom-table\" id=\"appointmentsTable\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>ID</th>\r\n");
      out.write("                            <th>Patient Name</th>\r\n");
      out.write("                            <th>Gender</th>\r\n");
      out.write("                            <th>Age</th>\r\n");
      out.write("                            <th>Date</th>\r\n");
      out.write("                            <th>Email</th>\r\n");
      out.write("                            <th>Contact</th>\r\n");
      out.write("                            <th>Condition</th>\r\n");
      out.write("                            <th>Address</th>\r\n");
      out.write("                            <th>Status</th>\r\n");
      out.write("                            <th>Doctor</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        ");

                        AppointmentDao dao = new AppointmentDao(DBConnect.getConn());
                        DoctorDao dao2 = new DoctorDao(DBConnect.getConn());
                        List<Appointment_entity> list = dao.getAllPatients();
                        
                        if(list != null && !list.isEmpty()) {
                            for(Appointment_entity ap : list){
                                Doctor_entity d = dao2.getDoctorDetails(ap.getDoct_id());
                        
      out.write("\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>");
      out.print(ap.getId());
      out.write("</td>\r\n");
      out.write("                            <td class=\"patient-name\">");
      out.print(ap.getApp_name());
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(ap.getApp_gender());
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(ap.getApp_age());
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(ap.getApp_contact());
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(ap.getApp_email());
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(ap.getApp_date());
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(ap.getApp_cond());
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print(ap.getApp_add());
      out.write("</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <span class=\"status-badge status-");
      out.print(ap.getApp_status().toLowerCase());
      out.write("\">\r\n");
      out.write("                                    ");
      out.print(ap.getApp_status());
      out.write("\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td class=\"doctor-name\">");
      out.print(d != null ? d.getDoc_name() : "N/A");
      out.write("</td>\r\n");
      out.write("                            \r\n");
      out.write("                        </tr>\r\n");
      out.write("                        ");

                            }
                        } else {
                        
      out.write("\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td colspan=\"12\" class=\"text-center py-5\">\r\n");
      out.write("                                <i class=\"fas fa-calendar-times text-muted\" style=\"font-size: 4rem;\"></i>\r\n");
      out.write("                                <h4 class=\"mt-3 text-muted\">No Appointments Found</h4>\r\n");
      out.write("                                <p class=\"text-muted\">There are currently no appointments in the system.</p>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        ");

                        }
                        
      out.write("\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
