/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-08-23 21:58:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.DAO.DoctorDao;
import com.db.DBConnect;
import com.entity.Doctor_entity;
import java.util.*;

public final class doctor_005fdashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/components/cdn-links.jsp", Long.valueOf(1753218954008L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1749728082234L));
    _jspx_dependants.put("jar:file:/D:/Abhinav_Eclipse/Hospital_Management_System/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Hospital_Management_System/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/admin/navbar.jsp", Long.valueOf(1755723643614L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.entity.Doctor_entity");
    _jspx_imports_classes.add("com.db.DBConnect");
    _jspx_imports_classes.add("com.DAO.DoctorDao");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Doctor Management - MediBridge</title>\r\n");
      out.write("<!-- Include CDN links -->\r\n");
      out.write("<!-- CDN Links File - Include this in your HTML files -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS should come first -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS should come at the end, before closing </body> or in <head> -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery (optional, if needed) -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Popper.js (optional, if using Bootstrap tooltips/popovers separately) -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.8/umd/popper.min.js\"></script>");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	background-color: #f8f9fa;\r\n");
      out.write("	font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar {\r\n");
      out.write("	background: #28a745 !important;\r\n");
      out.write("	box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-brand {\r\n");
      out.write("	color: white !important;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	font-size: 1.2rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-nav .nav-link {\r\n");
      out.write("	color: white !important;\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("	margin: 0 10px;\r\n");
      out.write("	text-transform: uppercase;\r\n");
      out.write("	font-size: 0.9rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-nav .nav-link:hover {\r\n");
      out.write("	background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".admin-dropdown {\r\n");
      out.write("	background: white;\r\n");
      out.write("	color: #28a745 !important;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	padding: 5px 15px;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main-content {\r\n");
      out.write("	padding: 30px 0;\r\n");
      out.write("	min-height: calc(100vh - 80px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-section {\r\n");
      out.write("	background: white;\r\n");
      out.write("	border-radius: 15px;\r\n");
      out.write("	padding: 30px;\r\n");
      out.write("	box-shadow: 0 5px 15px rgba(0, 0, 0, 0.08);\r\n");
      out.write("	height: fit-content;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-section h3 {\r\n");
      out.write("	color: #2c3e50;\r\n");
      out.write("	font-size: 1.5rem;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	margin-bottom: 25px;\r\n");
      out.write("	padding-bottom: 10px;\r\n");
      out.write("	border-bottom: 2px solid #28a745;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-label {\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	color: #495057;\r\n");
      out.write("	margin-bottom: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control, .form-select {\r\n");
      out.write("	border: 2px solid #e9ecef;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("	padding: 12px 15px;\r\n");
      out.write("	font-size: 0.95rem;\r\n");
      out.write("	transition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control:focus, .form-select:focus {\r\n");
      out.write("	border-color: #28a745;\r\n");
      out.write("	box-shadow: 0 0 0 0.2rem rgba(40, 167, 69, 0.25);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-submit {\r\n");
      out.write("	background: #28a745;\r\n");
      out.write("	border: none;\r\n");
      out.write("	color: white;\r\n");
      out.write("	padding: 12px 30px;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	font-size: 1rem;\r\n");
      out.write("	transition: all 0.3s ease;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-submit:hover {\r\n");
      out.write("	background: #218838;\r\n");
      out.write("	transform: translateY(-2px);\r\n");
      out.write("	box-shadow: 0 5px 15px rgba(40, 167, 69, 0.3);\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".details-section {\r\n");
      out.write("	background: white;\r\n");
      out.write("	border-radius: 15px;\r\n");
      out.write("	padding: 30px;\r\n");
      out.write("	box-shadow: 0 5px 15px rgba(0, 0, 0, 0.08);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".details-section h3 {\r\n");
      out.write("	color: #2c3e50;\r\n");
      out.write("	font-size: 1.5rem;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	margin-bottom: 25px;\r\n");
      out.write("	padding-bottom: 10px;\r\n");
      out.write("	border-bottom: 2px solid #28a745;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table {\r\n");
      out.write("	margin-bottom: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table thead th {\r\n");
      out.write("	background: #f8f9fa;\r\n");
      out.write("	color: #495057;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	border: none;\r\n");
      out.write("	padding: 15px 10px;\r\n");
      out.write("	font-size: 0.9rem;\r\n");
      out.write("	text-transform: uppercase;\r\n");
      out.write("	letter-spacing: 0.5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table tbody td {\r\n");
      out.write("	padding: 15px 10px;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("	border-color: #e9ecef;\r\n");
      out.write("	font-size: 0.9rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table tbody tr {\r\n");
      out.write("	transition: background-color 0.2s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table tbody tr:hover {\r\n");
      out.write("	background-color: #f8f9fa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-edit {\r\n");
      out.write("	background: #28a745;\r\n");
      out.write("	border: none;\r\n");
      out.write("	color: white;\r\n");
      out.write("	padding: 6px 15px;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	font-size: 0.8rem;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	transition: all 0.2s ease;\r\n");
      out.write("	margin-right: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-edit:hover {\r\n");
      out.write("	background: #218838;\r\n");
      out.write("	transform: translateY(-1px);\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-delete {\r\n");
      out.write("	background: #dc3545;\r\n");
      out.write("	border: none;\r\n");
      out.write("	color: white;\r\n");
      out.write("	padding: 6px 15px;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	font-size: 0.8rem;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	transition: all 0.2s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-delete:hover {\r\n");
      out.write("	background: #c82333;\r\n");
      out.write("	transform: translateY(-1px);\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table-responsive {\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".alert {\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( max-width : 768px) {\r\n");
      out.write("	.main-content {\r\n");
      out.write("		padding: 20px 0;\r\n");
      out.write("	}\r\n");
      out.write("	.form-section, .details-section {\r\n");
      out.write("		padding: 20px;\r\n");
      out.write("		margin-bottom: 20px;\r\n");
      out.write("	}\r\n");
      out.write("	.table thead th {\r\n");
      out.write("		font-size: 0.8rem;\r\n");
      out.write("		padding: 10px 5px;\r\n");
      out.write("	}\r\n");
      out.write("	.table tbody td {\r\n");
      out.write("		font-size: 0.8rem;\r\n");
      out.write("		padding: 10px 5px;\r\n");
      out.write("	}\r\n");
      out.write("	.btn-edit, .btn-delete {\r\n");
      out.write("		padding: 4px 8px;\r\n");
      out.write("		font-size: 0.7rem;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( max-width : 576px) {\r\n");
      out.write("	.navbar-nav .nav-link {\r\n");
      out.write("		font-size: 0.8rem;\r\n");
      out.write("		margin: 0 5px;\r\n");
      out.write("	}\r\n");
      out.write("	.admin-dropdown {\r\n");
      out.write("		padding: 3px 10px;\r\n");
      out.write("		font-size: 0.85rem;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- Navigation Bar -->\r\n");
      out.write("	");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>MediBridge: Administrator</title>\r\n");
      out.write("    \r\n");
      out.write("   ");
      out.write("<!-- CDN Links File - Include this in your HTML files -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS should come first -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS should come at the end, before closing </body> or in <head> -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery (optional, if needed) -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Popper.js (optional, if using Bootstrap tooltips/popovers separately) -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.8/umd/popper.min.js\"></script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            background-color: #f8f9fa;\r\n");
      out.write("        }\r\n");
      out.write("        .navbar-brand {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-link {\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            transition: color 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-link:hover {\r\n");
      out.write("            color: #ffc107 !important;\r\n");
      out.write("        }\r\n");
      out.write("        .dropdown-menu {\r\n");
      out.write("            border: none;\r\n");
      out.write("            box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15);\r\n");
      out.write("        }\r\n");
      out.write("        .dropdown-item:hover {\r\n");
      out.write("            background-color: #f8f9fa;\r\n");
      out.write("        }\r\n");
      out.write("        .content-area {\r\n");
      out.write("            margin-top: 2rem;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- to solve the issue of back button accessing the admin page you should remove the cache  -->\r\n");

response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");

if(session.getAttribute("adminObj") == null){
	response.sendRedirect("../Admin.jsp");
}


      out.write("   \r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark border-bottom\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"index.jsp\">\r\n");
      out.write("            <img src=\"../assets/logo.png\" alt=\"Logo\" width=\"35\" height=\"40\" \r\n");
      out.write("                 class=\"d-inline-block align-text-top me-2 rounded-circle\"\r\n");
      out.write("                 onerror=\"this.style.display='none'\">\r\n");
      out.write("            MediBridge\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <!-- Navbar toggler for mobile -->\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" \r\n");
      out.write("                data-bs-target=\"#navbarNavDropdown\" aria-controls=\"navbarNavDropdown\" \r\n");
      out.write("                aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarNavDropdown\">\r\n");
      out.write("            <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("                <li class=\"nav-item me-4\">\r\n");
      out.write("                    <a class=\"nav-link active\" aria-current=\"page\" href=\"../index.jsp\">\r\n");
      out.write("                        <i class=\"fa-solid fa-home me-1\"></i>Home\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("                <li class=\"nav-item me-4\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"doctor_dashboard.jsp\">\r\n");
      out.write("                        <i class=\"fa-solid fa-user-doctor me-1\"></i>Doctor\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("                <li class=\"nav-item me-4\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#\">\r\n");
      out.write("                        <i class=\"fa-solid fa-user-injured me-1\"></i>Patient\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                 \r\n");
      out.write("                <li class=\"nav-item me-4\">\r\n");
      out.write("                     <a class=\"nav-link\" href=\"../adminlogout\">\r\n");
      out.write("                         <i class=\"fa-solid fa-sign-out-alt me-2\"></i>Logout\r\n");
      out.write("                    </a>\r\n");
      out.write("               </li>       \r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Main Content -->\r\n");
      out.write("	<div class=\"main-content\">\r\n");
      out.write("		<div class=\"container-fluid\">\r\n");
      out.write("			<!-- Success/Error Messages -->\r\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row g-4\">\r\n");
      out.write("\r\n");
      out.write("				<!-- Add Doctor Form -->\r\n");
      out.write("				<div class=\"col-lg-4\">\r\n");
      out.write("					<div class=\"form-section\">\r\n");
      out.write("						<h3>Add Doctor</h3>\r\n");
      out.write("						<form id=\"addDoctorForm\" action=\"../addDoctor\" method=\"post\">\r\n");
      out.write("							<div class=\"mb-3\">\r\n");
      out.write("								<label for=\"fullName\" class=\"form-label\">Full Name</label> \r\n");
      out.write("								<input type=\"text\" class=\"form-control\" id=\"fullName\" name=\"doc_name\" required>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"mb-3\">\r\n");
      out.write("								<label for=\"dob\" class=\"form-label\">DOB</label> \r\n");
      out.write("								<input type=\"date\" class=\"form-control\" id=\"dob\" name=\"doc_dob\" required>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"mb-3\">\r\n");
      out.write("								<label for=\"qualification\" class=\"form-label\">Qualification</label>\r\n");
      out.write("								<input type=\"text\" class=\"form-control\" id=\"qualification\"\r\n");
      out.write("									name=\"doc_quali\" placeholder=\"e.g., MBBS, MD\" required>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"mb-3\">\r\n");
      out.write("								<label for=\"specialist\" class=\"form-label\">Specialist</label> \r\n");
      out.write("								<select class=\"form-select\" id=\"specialist\" name=\"doc_spec\" required>\r\n");
      out.write("									<option value=\"\">--select--</option>\r\n");
      out.write("									<option value=\"Cardiology\">Cardiology</option>\r\n");
      out.write("									<option value=\"Dermatology\">Dermatology</option>\r\n");
      out.write("									<option value=\"Dentist\">Dentist</option>\r\n");
      out.write("									<option value=\"Neurology\">Neurology</option>\r\n");
      out.write("									<option value=\"Orthopedic\">Orthopedic</option>\r\n");
      out.write("									<option value=\"Pediatrics\">Pediatrics</option>\r\n");
      out.write("									<option value=\"Psychiatry\">Psychiatry</option>\r\n");
      out.write("									<option value=\"General Medicine\">General Medicine</option>\r\n");
      out.write("									<option value=\"ENT\">ENT</option>\r\n");
      out.write("									<option value=\"Ophthalmology\">Ophthalmology</option>\r\n");
      out.write("								</select>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"mb-3\">\r\n");
      out.write("								<label for=\"email\" class=\"form-label\">Email</label> \r\n");
      out.write("								<input type=\"email\" class=\"form-control\" id=\"email\" name=\"doc_email\" required>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"mb-3\">\r\n");
      out.write("								<label for=\"mobNo\" class=\"form-label\">Contact No</label> \r\n");
      out.write("								<input type=\"tel\" class=\"form-control\" id=\"mobNo\" name=\"doc_contact\"\r\n");
      out.write("									placeholder=\"e.g., 9090909090\" required>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<button type=\"submit\" class=\"btn btn-submit\">\r\n");
      out.write("								<i class=\"fas fa-plus me-2\"></i> Add Doctor\r\n");
      out.write("							</button>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- Doctor Details Table -->\r\n");
      out.write("				<div class=\"col-lg-8\">\r\n");
      out.write("					<div class=\"details-section\">\r\n");
      out.write("						<h3>Doctor Details</h3>\r\n");
      out.write("						<div class=\"table-responsive\">\r\n");
      out.write("							<table class=\"table table-hover\">\r\n");
      out.write("								<thead>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<th>Full Name</th>\r\n");
      out.write("										<th>DOB</th>\r\n");
      out.write("										<th>Qualification</th>\r\n");
      out.write("										<th>Specialist</th>\r\n");
      out.write("										<th>Email</th>\r\n");
      out.write("										<th>Mob No</th>\r\n");
      out.write("										<th>Action</th>\r\n");
      out.write("									</tr>\r\n");
      out.write("								</thead>\r\n");
      out.write("								<tbody>\r\n");
      out.write("									");

									try {
										DoctorDao dao2 = new DoctorDao(DBConnect.getConn());
										List<Doctor_entity> list2 = dao2.getAllDoctor(); // Fixed method name
										
										if (list2 != null && !list2.isEmpty()) {
											for (Doctor_entity d : list2) {
									
      out.write("\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td>");
      out.print(d.getDoc_name());
      out.write("</td>\r\n");
      out.write("										<td>");
      out.print(d.getDoc_dob());
      out.write("</td>\r\n");
      out.write("										<td>");
      out.print(d.getDoc_quali());
      out.write("</td>\r\n");
      out.write("										<td>");
      out.print(d.getDoc_spec());
      out.write("</td>\r\n");
      out.write("										<td>");
      out.print(d.getDoc_email());
      out.write("</td>\r\n");
      out.write("										<td>");
      out.print(d.getDoc_contact());
      out.write("</td>\r\n");
      out.write("										<td>\r\n");
      out.write("											<button class=\"btn btn-edit\" onclick=\"editDoctor(");
      out.print(d.getId());
      out.write(")\">Edit</button>\r\n");
      out.write("											<button class=\"btn btn-delete\" onclick=\"deleteDoctor(");
      out.print(d.getId());
      out.write(")\">Delete</button>\r\n");
      out.write("										</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									");

											}
										} else {
									
      out.write("\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td colspan=\"7\" class=\"text-center text-muted py-4\">\r\n");
      out.write("											<i class=\"fas fa-user-md fa-2x mb-2\"></i><br> \r\n");
      out.write("											No doctors found. Add a doctor using the form on the left.\r\n");
      out.write("										</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									");

										}
									} catch (Exception e) {
										e.printStackTrace();
									
      out.write("\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td colspan=\"7\" class=\"text-center text-danger py-4\">\r\n");
      out.write("											<i class=\"fas fa-exclamation-triangle fa-2x mb-2\"></i><br> \r\n");
      out.write("											Error loading doctor data.\r\n");
      out.write("										</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									");

									}
									
      out.write("\r\n");
      out.write("								</tbody>\r\n");
      out.write("							</table>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		function editDoctor(doctorId) {\r\n");
      out.write("			// Redirect to edit page or open edit modal\r\n");
      out.write("			window.location.href = '${pageContext.request.contextPath}/EditDoctorServlet?id=' + doctorId;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function deleteDoctor(doctorId) {\r\n");
      out.write("			if (confirm('Are you sure you want to delete this doctor?')) {\r\n");
      out.write("				window.location.href = '${pageContext.request.contextPath}/DeleteDoctorServlet?id=' + doctorId;\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /admin/doctor_dashboard.jsp(248,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(false);
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("				<div class=\"alert alert-success alert-dismissible fade show\" role=\"alert\">\r\n");
        out.write("					<i class=\"fas fa-check-circle me-2\"></i>\r\n");
        out.write("					${succMsg}\r\n");
        out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"></button>\r\n");
        out.write("				</div>\r\n");
        out.write("				");
        if (_jspx_meth_c_005fremove_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("			");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fremove_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:remove
    org.apache.taglibs.standard.tag.common.core.RemoveTag _jspx_th_c_005fremove_005f0 = (org.apache.taglibs.standard.tag.common.core.RemoveTag) _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.common.core.RemoveTag.class);
    _jspx_th_c_005fremove_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fremove_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /admin/doctor_dashboard.jsp(254,4) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fremove_005f0.setVar("succMsg");
    // /admin/doctor_dashboard.jsp(254,4) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fremove_005f0.setScope("session");
    int _jspx_eval_c_005fremove_005f0 = _jspx_th_c_005fremove_005f0.doStartTag();
    if (_jspx_th_c_005fremove_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.reuse(_jspx_th_c_005fremove_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /admin/doctor_dashboard.jsp(257,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(false);
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("				<div class=\"alert alert-danger alert-dismissible fade show\" role=\"alert\">\r\n");
        out.write("					<i class=\"fas fa-exclamation-circle me-2\"></i>\r\n");
        out.write("					${errorMsg}\r\n");
        out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"></button>\r\n");
        out.write("				</div>\r\n");
        out.write("				");
        if (_jspx_meth_c_005fremove_005f1(_jspx_th_c_005fif_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("			");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fremove_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:remove
    org.apache.taglibs.standard.tag.common.core.RemoveTag _jspx_th_c_005fremove_005f1 = (org.apache.taglibs.standard.tag.common.core.RemoveTag) _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.common.core.RemoveTag.class);
    _jspx_th_c_005fremove_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fremove_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
    // /admin/doctor_dashboard.jsp(263,4) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fremove_005f1.setVar("errorMsg");
    // /admin/doctor_dashboard.jsp(263,4) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fremove_005f1.setScope("session");
    int _jspx_eval_c_005fremove_005f1 = _jspx_th_c_005fremove_005f1.doStartTag();
    if (_jspx_th_c_005fremove_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.reuse(_jspx_th_c_005fremove_005f1);
    return false;
  }
}
